### ISSUE TITLE
Wish: don't use ".lock" to mean "must be committed"

### ISSUE THREAD

**Issue by adamgit** [Carthage/Carthage#107]
Probably too late to change this now, but ...

I maintain comprehensive .gitignore files for ObjC dev. In my life as a sysadmin, lock files (both in Win and *nix systems) historically meant "this file is open locally, don't open it for editing" ... so, obviously: they're in the gitignore's. There are IDE's, and a lot of text/source-editors, today that still do this.

Cocoapods does many things that have caused me a lot of hassle to un-break, and it's great to see Carthage doing things better. But it's a shame to see Carthage copying the use of ".lock" to mean almost the opposite: "must be committed, contains critical source information required for building".

If at some point that extension could be changed into something that was more obviously related to source control, it would mean one less complicated app-specfic stanza in our gitignores everywhere :)

**Comment by mattdipasquale** [comment]
I don't understand why .lock was changed to .resolved.

Allow me to argue from the perspective of Bundler because I'm not familiar with Carthrage.

Sure, one might commit the Gemfile.lock file, but .lock doesn't mean "must be committed." It means the gems are locked. It works similarly to other (those you speak of) .lock files: It prevents you from running `bundle install`.

If you have other .lock files you need to ignore, put something like this in your Git `excludesfile`:

    *.lock
    !Gemfile.lock

See https://git-scm.com/docs/gitignore.

**Comment by jspahrsummers** [comment]
@mattdipasquale This decision was made in late 2014, with minimal pushback. It's not going to be changing, sorry.

**Comment by mattdipasquale** [comment]
"A foolish consistency is the hobgoblin of little minds." — Ralph Waldo Emerson, [*Self-Reliance*](http://www.emersoncentral.com/selfreliance.htm)

**Comment by robrix** [comment]
Since we don’t intend to change this decision, I’m going to lock the thread. Thanks for your input, everyone!
