### ISSUE TITLE
Failed to read file - Carthage 0.12 - ResearchKit

### ISSUE THREAD

**Issue by blender** [Carthage/Carthage#1077]
Since the recent release, Carthage 0.12  fails to build [ResearchKit](https://github.com/researchkit/researchkit) with `Failed to read file` . 

Works fine with 0.11

Try yourselves:

```
brew info carthage
brew switch carthage 0.11
```

**Comment by ikesyo** [comment]
I checked that repo and found that the `CFBundlePackageType` value of [the Info.plist](https://github.com/ResearchKit/ResearchKit/blob/429c3c988672ca969698a9f787f10e4c7b6478ed/ResearchKit/Info.plist#L15-L16) is `BNDL`, but we are only finding `FMWK` or `dSYM` since #1023.

Should we accept `BNDL` value? @Carthage/carthage
