### ISSUE TITLE
Error if user specifies `--use-submodules`, but `Carthage/Checkouts` is gitignored

### ISSUE THREAD

**Issue by mdiep** [Carthage/Carthage#1153]
https://github.com/Carthage/Carthage/issues/1146#issuecomment-187893400

**Comment by maximveksler** [comment]
Maybe a better solution would be to have carthage use `git submodule add --force` and produce a warning? Because it obviously logical for a user not want to push "junk" into his repo, but if he is using submodules not face the SNAFU situation my IKnowKungFu has reached prematurely ? 

As explained in https://github.com/Carthage/Carthage/issues/1146#issuecomment-188033898

**Comment by mdiep** [comment]
That sounds like a fair approach.

**Comment by ikesyo** [comment]
We already (originally) pass `--force` option to `git submodule add`: https://github.com/Carthage/Carthage/blob/0.24.0/Source/CarthageKit/Git.swift#L642.

The submodules those are subjects of #1146 was actually added in [this commit](https://github.com/maximveksler/IKnowKungFu/commit/c33fac7ca090723c6b3e4c1551fff6f524335c55) and then removed in [the subsequent commit](https://github.com/maximveksler/IKnowKungFu/commit/1de3fd845f06a906b38ca34d824e382133086dd5). So that is not a Carthage's fault.

Closing.

**Comment by maximveksler** [comment]
@ikesyo I can't agree it's not Carthage's fault because nothing touched the submodules setup of that repo other then Carthage. If using 'regular' flows of Carthage the repo because "unstable" that might mean additional consideration should be given as to the why it happened. 

I've since moved to using Swift Package Manager, so I'm unable to report if the issue persists in recent versions of Carthage or not.
