### ISSUE TITLE
Carthage update/build failures since v0.12 / #892 due to example projects in repo.

### ISSUE THREAD

**Issue by danthorpe** [Carthage/Carthage#1161]
I know that #892 has long since been closed and we've all moved on, and I guess I should have mentioned this a bit earlier... 

But, I've been getting some bug reports that now my framework doesn't build using Carthage (https://github.com/danthorpe/Operations/issues/200). It seems to be because I have some example projects in my frameworks repo. Carthage is now attempting to build them, and it fails:

> *** Building scheme "OS X Operations" in Operations.xcodeproj
> *** Building scheme "tvOS Operations" in Operations.xcodeproj
> *** Building scheme "watchOS Operations" in Operations.xcodeproj
> *** Building scheme "iOS Operations" in Operations.xcodeproj
> *** Building scheme "OS X Extensions Operations" in Operations_ExtensionCompatible.xcodeproj
> *** Building scheme "tvOS Extensions Operations" in Operations_ExtensionCompatible.xcodeproj
> *** Building scheme "iOS Extensions Operations" in Operations_ExtensionCompatible.xcodeproj
> *** Building scheme "Operations" in Permissions.xcworkspace
> ** BUILD FAILED **

The `Permissions.xcworkspace` above is `Examples/Permissions/Permissions.xcworkspace` - it's an example project which shows the framework consumer how to use the framework. The thing is, this project is setup using CocoaPods, mostly because I can use's the "development pods" features: e.g. here is the Podfile

```
platform :ios, '8.0'

inhibit_all_warnings!
use_frameworks!

pod 'Operations/', :path => '../../'
```

Additionally, the repo ignores the Pods folder. So, the examples fail to build directly from source (as you need to run `$ pod update` first).

Has anyone else noticed this? In terms of possible solutions:

1. Sure, I could include the Pods folder in those example - but I don't want to, unnecessarily increases the size of the repo.

2. Carthage could support some kind of optional, ignore configuration which the maintainer could add to mark Xcode projects as ignored. Sort of like a `.carthageignore` file.

3. Carthage could look for `Podfile` and or `Podfile.lock` files in the folders where it finds the `.xcodeproj` and either run `$ pod update` or skip the build if the `Manifest.lock ` is missing or doesn't match the `Podfile.lock`.

I'd have thought that this is a fairly common problem, as example projects inside the repo is a fairly standard practice. I did look though the existing issues but couldn't find anything that stuck out.

Thoughts?

**Comment by mdiep** [comment]
:disappointed: 

(3) is a no-go. I'm firmly against building CocoaPods-specific logic into Carthage.

(2) is a potential, but it'd probably fit better alongside something like #262, and I don't see that being a priority.

(1) seems like the best short-term solution. Or, set up the example project so that it doesn't require CocoaPods.

Sorry for the inconvenience. TBH, this is why I dislike CocoaPods: it uses a lot of magic instead of simply automating the standard way of doing things.

**Comment by danthorpe** [comment]
@mdiep yep, I've done 1 for now. I'm interested to hear how other framework maintainers are getting round this issue. 

Carthage doesn't have the concept of "local dependencies" - i.e. link to a local .xcodeproj right? And if you have a project, inside a repo, which has a Cartfile which points to the repo, do you get a recursive checkout/build problem? And developing an example while pointing to a remote is a really slow way of developing.

So... how do the Carthage maintainers recommend including Example projects inside Carthage compatible repos?

**Comment by mdiep** [comment]
> So... how do the Carthage maintainers recommend including Example projects inside Carthage compatible repos?

Carthage builds any shared dynamic framework scheme in the project. If a particular scheme is shared through both an `xcodeproj` and an `xcworkspace`, Carthage will build it through the latter.

The reason that your example fails is that CocoaPods is generating an `xcscheme` for Operations in `Pods.xcodeproj`, which Carthage tries to build through `Permissions.xcworkspace`—because of the above criteria. If you include a shared dynamic framework scheme, it must be buildable out of the box.

But you shouldn't need to use CocoaPods for the example project. You already have `Operations.xcodeproj`, which knows how to build your framework. You should be able to add that to `Permissions.xcworkspace` directly—without CocoaPods. Then you'll be able to build the example project and eliminate the shared framework scheme from CocoaPods that Carhage is trying to build.

Does that make sense?
