### ISSUE TITLE
iTunes Connect submission issue

### ISSUE THREAD

**Issue by zdenektopic** [Carthage/Carthage#1196]
Hello,

I am using Carthage for Async and RxSwift, RxCocoa frameworks. I have copy-frameworks Build Run Phase properly setup but appstore rejects the build every time with multiple errors like ITMS-90087.

The issue is obviously with frameworks having symbols for i386 and x86_64 architectures.

<img width="1114" alt="snimek obrazovky 2016-03-19 v 18 07 49" src="https://cloud.githubusercontent.com/assets/2551911/13900052/8be22cf6-edfd-11e5-8848-9d32426f463e.png">

**Comment by mdiep** [comment]
If you're using `copy-frameworks`, then the frameworks shouldn't have x86 architectures.

**Comment by zdenektopic** [comment]
Well, as you can see it does.

I solved it with this: http://stackoverflow.com/a/30866648
However, we've got this from apple:
> Dear developer,
> 
> We have discovered one or more issues with your recent delivery for "Mapy.cz". Your delivery was successful, but you may wish to correct the following issues in your next delivery:
> 
> Too many symbol files - These symbols have no corresponding slice in any binary [0C8B86A1-6C1A-342C-9D8D-2C21959C0548.symbols, 2C19BD07-7AC8-3B4C-9E2D-27B4BA944760.symbols, 72221540-DB99-3474-A970-C66A6685C812.symbols, 7A46839F-2913-3C9C-96B3-C531EA21575D.symbols, C7886111-D3CB-3AE9-987B-BAD0AE9497D2.symbols, F70CE884-045D-355F-A9E5-07156F09FF4F.symbols]
> 
> After you’ve corrected the issues, you can use Xcode or Application Loader to upload a new binary to iTunes Connect.
> 
> Regards,
> 
> The App Store team
>

**Comment by zdenektopic** [comment]
Something came to mind. It takes Valid architectures from build settings right? I mean "copy-frameworks". So in Release configuration there should be no i386 and x86_64 probably?

**Comment by mdiep** [comment]
I don't believe the `Valid Architectures` setting should ever contain i386 or x86_64 for iOS frameworks.

**Comment by zdenektopic** [comment]
But copy frameworks script takes Valid arxhitectures from main/app projects, doesnt it? We have i386 and x86 for release build set in the app project.

**Comment by hyperspacemark** [comment]
What version of Carthage are you using? This particular iTunes Connect submission error occurs when you're copying dSYMs for architecture slices that have been stripped from the frameworks by `carthage copy-frameworks`. Since Carthage 0.12, `copy-frameworks` has been copying the necessary dSYMs in addition to frameworks (See #1023). Can you ensure that you're not manually copying dSYMs into the build product as was recommended prior to 0.12?

**Comment by hiteshsondhi88** [comment]
Hey Guys

I am getting the same message from Apple every time I do submit the app. Do you have any idea what might be causing this ?

Just as a note I am on carthage 0.16.2

**Comment by mikemee** [comment]
I'm running Carthage 18.1 now, but was also seeing something similar in Carthage 18. 

@zdenektopic and @hiteshsondhi88 I think I found the source of the problem and a fix. It would be great if you could verify.

I was able to fix this problem by removing extraneous entries in Targets -> General , Embedded Binaries section. I had two Carthage-supplied frameworks listed in Embedded Binaries that were also listed right below in "Linked Frameworks and Libraries".  Those 2 frameworks were the ones causing the ITMS-90087 errors when I tried to submit (due to X86 & i386 being included). (My guess is that these were here because we'd been developing these in-house -- the clue was another Carthage framework that was _not_ on the Embedded Binaries list).

When I removed the Embedded Binaries, this also removed a copy action from the Build Phases. I suspect this was copying over the files over the top of whatever the Run Carthage Script phase was doing correctly.

Hope this helps...

**Comment by mikemee** [comment]
Hmm, it was part of the project file cleanup, which I'm sure I used last week... but ...

On the plus side, I seem to be able to submit with the defaults this week, instead of unchecking the "use bitcode" which seemed to be necessary on prior attempts.

**Comment by ikesyo** [comment]
What @mikemee said above should be the answer. Closing.
