### ISSUE TITLE
carthage update stuck

### ISSUE THREAD

**Issue by rmuhamedgaliev** [Carthage/Carthage#1219]
I have issue with get dependencies on `carthage update`. 

_Cartfile_

```
github "ReactiveX/RxSwift"
github "ReactiveCocoa/ReactiveCocoa"
github "antitypical/Result"
github "Moya/Moya"
github "nixzhu/KeyboardMan"
git "https://github.com/SwiftyJSON/SwiftyJSON.git"
github "Alamofire/Alamofire"
github "Haneke/HanekeSwift"
github "mamaral/Neon"
```

After run command it stuck:

> **\* Cloning Neon
> **\* Cloning HanekeSwift
> **\* Cloning Alamofire
> **\* Cloning SwiftyJSON
> **\* Cloning KeyboardMan
> **\* Cloning Moya
> **\* Cloning Result
> **\* Cloning ReactiveCocoa
> **\* Cloning RxSwift

Version

> carthage version
> 0.15.2

**Comment by mdiep** [comment]
This typically happens when Carthage can't find compatible versions of your dependencies. It's looking at all possible permutations of the versions of your dependencies to find a compatible set, but hasn't exhausted all options yet.

Specifying versions in your `Cartfile` should help. `github "ReactiveCocoa/ReactiveCocoa" ~> 3.0`, etc.

**Comment by rmuhamedgaliev** [comment]
@mdiep nope, it's not work. Can I get verbose output of process? ```--verbose``` not work

**Comment by mdiep** [comment]
No, the resolver doesn't currently print any output. :disappointed:

For now, you unfortunately need to compare the dependencies manually.

**Comment by rmuhamedgaliev** [comment]
Can i enable verbose or debug logging for check state process?

**Comment by mdiep** [comment]
No. :disappointed:

**Comment by robertjpayne** [comment]
This is happening to me, the cause of it for myself was a dependency with no shared schemes. Would be better if Carthage just detected this and threw an error as it's frustrating to find out what's wrong.

**Comment by Jonathan-Gwilliams** [comment]
I recently had this occur because my ssh key's passphrase had not been updated in my keychain after being changed. You'll soon know this is the case because if you pull the git repository you're trying to include using Carthage it'll ask you for your passphrase. Running ssh-add again and updating the passphrase fixed the issue for me.

**Comment by andreiverdes** [comment]
This worked!

**Comment by jack0817** [comment]
@Jonathan-Gwilliams nailed it!

**Comment by inPhilly** [comment]
Thank you Jonathan! I never would have figured that out!

**Comment by leilahsimona** [comment]
This is still saving butt's in the 2018, thanks @Jonathan-Gwilliams

**Comment by PeterAntonsen** [comment]
Jonathan-Gwilliams, You rock!
