### ISSUE TITLE
Is there a way to blacklist frameworks to build?

### ISSUE THREAD

**Issue by crenwick** [Carthage/Carthage#1250]
`carthage update` can take a _really_ long time to build sometimes, and in some cases, it spends most of its time building frameworks that I don't need, but are attached to libraries anyway.

For example, https://github.com/Moya/Moya brings in `ReactiveCocoa/ReactiveCocoa`  and `ReactiveX/RxSwift` even though they are optional libraries to Moya itself (in other words, Moya includes some helper functions for those libraries, but neither are required to use and build Moya). This means that Carthage not only has to build for both of these libraries, but all of _their_ dependencies as well.

Another example is https://github.com/danielgindi/Charts. Just by bringing in Charts through Carthage means I have to spend time building `Charts-Realm` and the entire `Realm` framework -- neither of which I use for my app or are even essential to using Charts in the first place.

CocoaPods gets around this with the concept of 'subpods', which I'm aware that Carthage is not interesting in doing.

As a hack, I was able to shave ~15 minutes off of my apps' `carthage update` time by forking Moya and removing ReactiveCocoa and RxSwift -- but that means that I now have to maintain my own fork of Moya and continue to rebase that fork each time I was to update. And now I'm looking to do the same thing for Charts...

Is there anything I can do on the client side of the framework of avoid such needless build times? 
Can I specify a blacklist of sorts, that lets carthage know to never build? 
If not, are ya'll open to exploring a solution (either that be a blacklist or something else entirely)?

**Comment by mdiep** [comment]
There isn't a way to blacklist frameworks. And I'm not too interested in adding one as it adds complexity and adds very little benefit to most people. It is something we could consider down the road. We've talked about adding some form of project settings, which would enable this sort of thing, but we've been busy making more impactful contributions. (And, sadly, we don't have very many contributors.)

But building your app's dependencies shouldn't be a frequent operation. You could ask project maintainers to upload pre-built binaries for Carthage to use. Otherwise, if you're looking to reduce CI times, you could consider using something like [carthage_cache](https://github.com/guidomb/carthage_cache).

**Comment by jeeftor** [comment]
I dont know if you are doing CI or local builds but i totally agree that its a PIA to deal with big carthage files.  In our CI server we've ended up hacking up a bit to save time:

1 build task detects if there is any change in the `Cartfile` or `Cartfile.resolved` and runs `carthage bootstrap --platform ios --no-use-binaries` and zips up the entire `Carthage` directory

The other build task (the one we use normally) - just pulls down and unzips that `Carthage` directory.

Doing this allows us to build our main app in about 4 mins while the carthage stuff takes about 28 mins to build.  HUGE improvement. 

An issue we have is that we have a core set of libs that are in carthage and 3 apps that work off those core libs - any change to the core although infrequent still is VERY Slow to propagate around.

**Comment by ikesyo** [comment]
Let's merge this into #1227 and #1990.
