### ISSUE TITLE
libswiftAppKit.dylib provides version 0.0.0

### ISSUE THREAD

**Issue by akaralar** [Carthage/Carthage#1279]
When I run `carthage update` with the `Cartfile` below, I get the error below. What might be causing this, does anybody have an idea?

* `carthage version`: 0.16.2, installed via Homebrew

**Cartfile**
```
github "nakiostudio/EasyPeasy"
```

**Carthage Output**
```
± ❯ carthage update
dyld: Library not loaded: @rpath/libswiftAppKit.dylib
  Referenced from: /usr/local/bin/carthage
  Reason: Incompatible library version: carthage requires version 1.0.0 or later, but libswiftAppKit.dylib provides version 0.0.0
[1]    7810 trace trap  carthage update
```

**Comment by sharplet** [comment]
FWIW, I had the same issue. I worked around it by using the [package installer](https://github.com/Carthage/Carthage/releases/download/0.16.2/Carthage.pkg).

**Comment by Goles** [comment]
I'm also experiencing the same issue, any idea of how to fix homebrew updating for Carthage?

**Comment by ianbytchek** [comment]
Check if you have `/Library/Frameworks/CarthageKit.framework`, after deleting it everything got back to normal.

Just updated from a very old version, for some reason Homebrew wasn't even aware of local Carthage installation. Perhaps it was installed manually with package installer, it copied some stuff into `/Library/Frameworks`. Later, when installed with Homebrew, it pulls libs from the old location instead of `/usr/local/Cellar/carthage/…/Frameworks/CarthageKit.framework`.

I guess Homebrew formula should check for that conflict or Carthage should link against a specific framework?

P. S. Should libswiftAppKit.dylib even be there? On my system it's found only in two places: CommandLineTools and CarthageKit.

**Comment by jaderfeijo** [comment]
Downloading the package installer and installing it solved the problem for me.

**Comment by akaralar** [comment]
@ianbytchek removing the file solved it for me too. apparently I previously installed via package installer before brew. thanks!

**Comment by jamesmudgett** [comment]
Installing the package worked!, Thanks.

**Comment by jcampbell05** [comment]
Does anyone know the underlying reason for this error ? I have this issue in a project and I wish to fix it.
