### ISSUE TITLE
How to change the framework source code?

### ISSUE THREAD

**Issue by TheCodeor** [Carthage/Carthage#1282]
How to change the framework source code?

**Comment by mdiep** [comment]
I'm not sure what you're asking.

**Comment by TheCodeor** [comment]
I'm sorry, my English is very bad.I want to ask is Carthage to support to their own needs in accordance with custom modifications library source files?

**Comment by mdiep** [comment]
If you use `carthage build` as a separate step, you can make modifications to your dependencies to test them. But you need to be careful because `update`, `bootstrap`, and `checkout` will wipe your modifications.

You can also use `--use-submodules`. And you can add your dependencies Xcode projects directly to your Xcode project instead of using `carthage build`. Just make sure you don't lose your work accidentally!

Let us know if you need more help.

**Comment by davidbjames** [comment]
For anyone coming to this, I want to validate what Matt suggested to add the Xcode project directly (presumably a separate checkout somewhere on your computer). There is literally no step 2! Xcode is smart enough to use the embedded Xcode source and not the referenced Carthage framework.
