### ISSUE TITLE
xcodebuild timed out while trying to read dependency

### ISSUE THREAD

**Issue by diogoguimaraes** [Carthage/Carthage#1283]
* `carthage version`: 0.16.2 
* `xcodebuild -version`: 7D175
* Are you using `--no-build`? No
* Are you using `--no-use-binaries`? No
* Are you using `--use-submodules`? No

**Cartfile**
```
github "mattwyskiel/LicensesKit" "master"
```

**Carthage Output**
```
xcodebuild timed out while trying to read LicensesKit.xcodeproj
```
The log file has no errors and the dependencies build was successful.

Do you have any idea of what may be causing this?

**Comment by mdiep** [comment]
This is a bug in xcodebuild that affects some projects. Unfortunately, I'm not sure what causes it or how to work around the issue. But if you find something that works, please let us know!

**Comment by ikesyo** [comment]
That is because that the `LicenseKit.xcodeproj` in the root dir does not have any shared schemes nor user-specific schemes if the project is not opend by Xcode, so that let `xcodebuild -list` hang. If you open the project once, Xcode would prepare autocreated schemes for the current user, the the command should succeed.

Alternatively, instead of having framework schemes in the separeted `LicensesKitCarthage/LicensesKitFramework.xcodeproj`, you can setup the framework schemes to `LicenseKit.xcodeproj`. I think that should work correctly.
