### ISSUE TITLE
Carthage not finding Mac platform targets

### ISSUE THREAD

**Issue by kstenerud** [Carthage/Carthage#1289]
* `carthage version`: 0.15.2
* `xcodebuild -version`: 7.3 (7D175)
* Are you using `--no-build`? No
* Are you using `--no-use-binaries`? No
* Are you using `--use-submodules`? No

**Cartfile**
```
github "kstenerud/KSCrash" ~> 1.5
```

**Carthage Output**
```
$ carthage update --platform OSX
*** Fetching KSCrash
*** Checking out KSCrash at "1.5.5"
*** xcodebuild output can be found in /var/folders/nv/kbqb5fp9373d5sn1ybr2gfkh0000gn/T/carthage-xcodebuild.C7AbpS.log
*** Skipped building KSCrash due to the error:
Dependency "KSCrash" has no shared framework schemes for any of the platforms: Mac

If you believe this to be an error, please file an issue with the maintainers at https://github.com/kstenerud/KSCrash/issues/new
```

Except that there is a shared framework scheme for Mac:

![screen shot 2016-05-01 at 11 30 38 am](https://cloud.githubusercontent.com/assets/245857/14943499/31ae9d64-0f90-11e6-8089-e69de0a36b10.png)
![screen shot 2016-05-01 at 11 31 46 am](https://cloud.githubusercontent.com/assets/245857/14943506/53b2f860-0f90-11e6-8309-db91e841ee5e.png)

**Comment by ikesyo** [comment]
The problem is that the target's `MACH_O_TYPE` setting is `Static Library`, but Carthage only takes care of `Dynamic Library` (Dynamic Frameworks). So you should set `Dynamic Library` for the setting.

<img width="1072" alt="2016-05-02 13 13 55" src="https://cloud.githubusercontent.com/assets/909674/14947095/39df4f46-1068-11e6-879f-9484d14f930c.png">
