### ISSUE TITLE
[question][enhancement] Organise Build directory into sub directories

### ISSUE THREAD

**Issue by danielphillips** [Carthage/Carthage#1304]
I have a bunch of dependancies and today I want to remove one. I have bit code enabled and as such in my Build/ directory I have all my frameworks, all their corresponding dSYM files and a ton of bcsymbolmap files. Each framework will be associated with a few of those bcsymbolmap files.

I check the build directory into my git repo.

When I want to remove a dependancy there is no way to find out which `bcsymbolmap` files are associated with a given framework, and as such I am unable to "clean up" my build folder without deleting everything and calling `carthage update` again.

I am wondering if it's a reasonable enhancement request to suggest that the build folder be organised with a sub directory for each dependancy, which would contain all `bcsymbolmap` files, the dSYM and the framework itself.

Any thoughts?

I hope it's appropriate for me to post here.

**Comment by hardikdevios** [comment]
#1288 check 3rd query somewhat similar to me mate, i am also stuck when it comes to removing lib its very tough to check that mapping. But good suggestion regarding sub directory option +1

**Comment by mdiep** [comment]
I think this would break compatibility with existing projects (which might rely on the location of the build directory), so it's a no-go.

But I think something like #902—deleting old `bcsymbolmap`s when building—is a better idea anyway. Or we should otherwise provide a map from frameworks to `bcsymbolmap`s. Maybe Carthage should create a symlink from `FrameworkName.bcsymbolmap` to the UUID version? That would give you an easy way to look them up in either direction and delete any unused versions.

> I hope it's appropriate for me to post here.

Yup! Totally appropriate. 😄

**Comment by ikesyo** [comment]
> Maybe Carthage should create a symlink from FrameworkName.bcsymbolmap to the UUID version? That would give you an easy way to look them up in either direction and delete any unused versions.

This would be a bit difficult because bcsymbolmap files are created per architecture, so there are multiple symbolmap files for a single framework.

**Comment by ikesyo** [comment]
Closing this in favor of #902 and #2333.
