### ISSUE TITLE
Manual code changes

### ISSUE THREAD

**Issue by Zyphrax** [Carthage/Carthage#1311]
I'm currently using CocoaPods but Charthage has caught my eye. Sometimes you're using an open source framework but it requires a small hotfix. With CocoaPods I would simply change the source, but how would I do that with Carthage?

**Comment by mdiep** [comment]
The ideal way is to submit a PR to the source project. :smile:

But you can also:

1. Fork the repo and make the change on your fork
2. Use `--no-build` and make the change locally. But I wouldn't recommend that outside of testing because doing another `update`/`bootstrap`/`checkout` will override your changes.

**Comment by Zyphrax** [comment]
Thank you, yeah PR is the best option, unfortunately some projects are like a ghost town :)

Anything else I should be mindful of in comparison with CocoaPods?

**Comment by mdiep** [comment]
> Anything else I should be mindful of in comparison with CocoaPods?

Not that I can think of!
