### ISSUE TITLE
[question] Framework Search Paths? (access Carthage frameworks from subproject)

### ISSUE THREAD

**Issue by drosenstark** [Carthage/Carthage#1313]
I'm using Carthage successfully in my Xcode project. One subproject, also a framework, relies on some of the dependencies in the Cartfile. To get the subproject to compile, I've added `$(PROJECT_DIR)/../Carthage/build/iOS` to my `Framework Search Paths`. This works, but it's brittle to changes in the subproject location.

Is there a better/right way of doing this? Thanks!

* `carthage version`:  0.16.2
* `xcodebuild -version`:  7.3.1/7D1014
* Are you using `--no-build`? no
* Are you using `--no-use-binaries`? no
* Are you using `--use-submodules`? no

**Cartfile**
```
github "Alamofire/Alamofire" ~> 3.3
github "robb/Cartography" "master"
github "SwiftyJSON/SwiftyJSON"
github "nschum/SwiftCGRectExtensions"
github "https://github.com/drosenstark/SimpleAlert.git" "trying-carthage"
github "dennisweissmann/DeviceKit" ~> 0.3.2
```

**Comment by mdiep** [comment]
You should be able to add `$(PROJECT_DIR)/Carthage/Build/iOS` to the search paths—Carthage will build the dependency first and make it available.

**Comment by drosenstark** [comment]
Hi there and thanks! **Carthage is unaware of my Xcode subproject (which is a git submodule).** 

I attempted:
- Delete Carthage directory
- Add a Cartfile to the submodule directory
- Update using `--use-submodules` (after deleting the `Carthage` folder). 

This did **not** place new copies of the Carthage-built libs anywhere. 

**Not sure where to proceed from here** (and aware that I've missed something basic). Thanks!

**Comment by mdiep** [comment]
If you have a framework in a separate repository that also wants to use dependencies from Carthage, you should give it a `Cartfile` and add it to your application's `Cartfile`. Then it will receive its own copies of the dependencies and will be able to relocate.

**Comment by noahcgreen** [comment]
> you should give it a Cartfile and add it to your application's Cartfile
Could you elaborate on this, please? What should be added to the parent Cartfile?

**Comment by mdiep** [comment]
```
git "url-to-child-repository"
```

**Comment by freemansion** [comment]
Let’s say we have following workspace:
- main project **A** which uses framework **X**.
- subproject **B** (git submodule) which also needs to use **X**. 

As @drosenstark wrote, he has added Framework Search Path `$(PROJECT_DIR)/../Carthage/build/iOS` for the subproject, just to be able to compile. But " it's brittle to changes in the subproject location.", with what I totally agree.

@mdiep’s comment says, that we have to have 2 Cartfiles (correct me if I wrong), for the **A** and **B** projects respectively.

So currently I have following questions:
1) Does it means that we have to build two versions of **X.framework**? (Otherwise, why do we need two Cartfile files)
2) Which Carthage command should be used to build frameworks? (I’m using `carthage bootstrap --platform ios` for both)
2) Which of the frameworks should be linked with **B**?  (A.X or B.X?)

Note: In case of **B.X.framework** (from `B/Carthage/Build/iOS` folder) linked with **B**, AppStore validation steps fails with 3 following errors: 
1. CFBundlerIdentifier Collision. There is more than one bundle with CFBundleIdentifier value under iOS application.
2. Invalid Bundle. The bundle contains disallowed nested bundles.
3. Invalid Bundle. The bundle contains disallowed file "Frameworks".

Which kind of make sense. But still not really understand how to make it work in a right way.

I will appreciate if anyone who has experience with building similar project share the information.
