### ISSUE TITLE
Broken dependency graph.

### ISSUE THREAD

**Issue by calebd** [Carthage/Carthage#1328]
`carthage update --no-build` fails in different ways with different combinations of dependencies.

Some combinations cause it to show a "dependency cycle" error. Some combinations cause it to to say "no version satisfies the requirement". Some combinations cause it to select incorrect (out of date) versions.

Clearing any Carthage and Xcode state has no effect.
- Carthage version: 0.16.2
- Xcode version: 7.3.1

**Comment by calebd** [comment]
This is possibly related to #1171.

**Comment by JaviSoto** [comment]
Sharing the contents of your Cartfile if possible would be really useful to try to reproduce 👍

**Comment by calebd** [comment]
@JaviSoto I know. It is fairly complex and almost entirely private.

**Comment by calebd** [comment]
Well. I guess it can't hurt.

## App Cartfile

```
github "TTTAttributedLabel/TTTAttributedLabel"
github "soffes/SSPullToRefresh"
github "JonasGessner/JGProgressHUD"
github "venmo/Static" ~> 1.1.0
github "AFNetworking/AFNetworking" ~> 3.1.0

github "hodinkee/Everest"
github "hodinkee/Escapement"
github "hodinkee/Sterling" ~> 1.3.0
github "hodinkee/Syndicate" ~> 1.4.2
github "hodinkee/Boutique" ~> 1.4.4
github "hodinkee/Tourbillon" ~> 1.1.0
```

## Everest Cartfile

```
github "hodinkee/Iris" ~> 1.1
github "hodinkee/Alexander" ~> 3.1
github "ReactiveCocoa/ReactiveCocoa" ~> 4.1
```

## Escapement Cartfile

```
github "hodinkee/Alexander" ~> 3.1
```

## Sterling Cartfile

```
github "hodinkee/Alexander" ~> 3.1
github "ReactiveCocoa/ReactiveCocoa" ~> 4.1
github "hodinkee/Hyperdrive" ~> 0.3.0
```

## Syndicate Cartfile

```

github "AliSoftware/Dip" ~> 4.1
github "AFNetworking/AFNetworking" ~> 3.1

github "hodinkee/Everest"
github "hodinkee/Pneumatic" ~> 1.2
```

## Boutique Cartfile

```
github "AliSoftware/Dip" ~> 4.1
github "shopify/mobile-buy-sdk-ios" == 1.2.4

github "hodinkee/Everest" ~> 0.67
```

## Tourbillon Cartfile

```
github "hodinkee/AstronomyKit" ~> 1.5
```

## Pneumatic Cartfile

```
github "daltoniam/Starscream" ~> 1.1.3
```

**Comment by calebd** [comment]
From what I can tell, Carthage does not handle cases where `A -> B, C`, `B -> D`, and `C -> D`. It also does not like cases where `A -> B, C` and `B -> C`.

I normally try to explicitly declare dependencies at every level they are used instead of relying on the presence of a dependency of a dependency. That is almost always the source of trouble.

**Comment by jakemarsh** [comment]
fwiw, I just landed from a Google search after having the exact same issue as @calebd.

My situation is an `A -> B, C`, while `B -> D`, and `C -> D`. 

When I run `carthage update --platform iOS --no-use-binaries` I get the _"The dependency graph contained a cycle..."_ error message.

**Comment by mdiep** [comment]
Can you share the full error that Carthage prints? `A -> (B, C), B -> (D), C -> (D)` isn't producing an error in my test. The information in the error should make it so I can create a test.

**Comment by jakemarsh** [comment]
Sorry, I actually ended up resolving this error by deleting the file here:

```
/Users/jakemarsh/Library/Caches/org.carthage.CarthageKit/dependencies/Infinity/index.lock
```

I ended up realizing that the nature of the dependencies (i.e. `A -> B, C`, while `B -> D`, and `C -> D`. ) wasn't the issue at all.

I started removing dependencies and ended up with a super simple `Cartfile` that still produced the _"The dependency graph contained a cycle..."_ error message.

At this point I realized something must have gone really wrong at some point in the past without me realizing, likely a crashed git process or something.

My apologies for hijacking your thread!

**Comment by erichoracek** [comment]
Hope I can help out here—I was the one that added the algorithm that emits the "dependency graph contained a cycle" error in the first place. This algorithm also emits that same error if the dependency graph passed to it is malformed. If there is a node specified as a dependency (e.g. `A` is declared as depending on `B`, but `B` is not included in the list of nodes passed into the algorithm), it will error in the same was as if there was a cycle. You can see both the "cycle" and "malformed" cases here: https://github.com/Carthage/Carthage/blob/master/Source/CarthageKitTests/AlgorithmsSpec.swift#L104-L133

I believe when I spoke with @calebd with this briefly when he was first encountering that error it was because of that issue. Sounds like we need to improve the error message to explain both of those cases being a possibility—I can do so in a pull request now.

Unfortunately, I wouldn't know why this algorithm is being passed a malformed graph in the first place. The code where that occurs is here: https://github.com/Carthage/Carthage/blob/master/Source/CarthageKit/Project.swift#L586-L619

**Comment by mdiep** [comment]
Since it seems like a malformed graph is an error on Carthage's part, I think it'd be best to keep the error as-is. If anything, I'd like to add a `fatalError` or something that checks that the graph is well formed.

If anyone can share the full error as printed by Carthage with the graph, that should be very helpful in understanding and fixing the issue.

**Comment by erichoracek** [comment]
I believe that either scenario would be considered to be a fatal error on Carthage's part. Dependency cycles should be caught in advance via the `carthage update` that produced the current `Cartfile.resolved`—not via the build order resolution step that produced this error.

**Comment by mdiep** [comment]
A malformed graph indicates an error on Carthage's part, so I think it should be a die horribly sort of fatal error.

Dependency cycles _should_ be caught in advance, but should provide a friendlier `CarthageError`-type error because it's possible to create one by hand editing a `Carthage.resolved` file.

**Comment by calebd** [comment]
I updated my `Cartfile` configuration above. There are still dependency version issues.

#### Carthage 0.16.2

`carthage update --no-build` selects the wrong version of `hodinkee/Boutique` (`1.4.4` instead of  `1.5.1`). If I lock `hodinkee/Boutique` to `~> 1.5.1`, it selects the wrong version of `hodinkee/Everest` (`0.67.0` instead of `0.70.0`).

#### Carthage 0.17.1

`carthage update --no-build` stalls while fetching `hodinkee/Alexander`. It never finishes.

**Comment by mdiep** [comment]
> carthage update --no-build selects the wrong version of hodinkee/Boutique (1.4.4 instead of 1.5.1). If I lock hodinkee/Boutique to ~> 1.5.1, it selects the wrong version of hodinkee/Everest (0.67.0 instead of 0.70.0). If I lock or remove hodinkee/Everest in the app Cartfile, Carthage gets stuck fetching various different libraries.

It sounds like you have a conflict of some sort between some of those dependencies. You don't seem too have all your `Cartfile`s above, and it's very hard to diagnose this without access to the repositories.

> carthage update --no-build stalls while fetching hodinkee/Alexander. It never finishes. Modifying the app Cartfile as I mentioned above has the same results in both 0.17.1 as it does in 0.16.2.

That's #1370. I have a PR open to fix it, but we're a little stalled on the Travis CI problems today. Hopefully I'll have a release out tomorrow that fixes it.

**Comment by calebd** [comment]
@mdiep All significant `Cartfile`s are present in my comment. The ones that are missing have no dependencies. I've tried to pare down the number of dependencies involved to produce a smaller test scenario but the issue is non-deterministic and the behavior changes when I do that. I will continue trying to find the right combination of things.

**Comment by calebd** [comment]
Here we go.

# App Cartfile

```
github "hodinkee/Everest" ~> 0.70.0
github "hodinkee/Boutique" ~> 1.4.4
```

# Everest Cartfile

```
github "hodinkee/Iris" ~> 1.1
github "hodinkee/Alexander" ~> 3.1
github "ReactiveCocoa/ReactiveCocoa" ~> 4.1
```

# Boutique Cartfile

```
github "AliSoftware/Dip" ~> 4.1
github "shopify/mobile-buy-sdk-ios" == 1.2.4
github "hodinkee/Everest" ~> 0.67
```

This combination of things causes Carthage to select the wrong version of `Boutique`. `Alexander` and `Iris` do not have `Cartfile`.

**Comment by erichoracek** [comment]
As a heads up, I've found that this error can also occur when the `Cartfile.resolved` is manually edited into the following state:
- Dependency `A` updated by hand to a new version in the `Cartfile.resolved`
- The new version of the `A` dependency now depends on `B`, which it did not previously
- The user that manually edited the Cartfile.resolved did not include the new version of `B` in their edit of the `Cartfile.resolved`
- When resolving the dependency graph, carthage finds dependency `A` and `B` both need to be built
- Since `B` is not passed into the topological sort as a node of the dependency graph (only as a relationship, since it is not in the `Cartfile.resolved`), it is recognized by the algorithm as a dependency cycle

My recommendation would be to add an extra error to the output in this scenario, along the lines of:

> The dependency graph either:
> - Contained a cycle
> - Was manually modified to be in an invalid state. Try retrying after performing a `carthage update`.

Perhaps we can reopen #1335 with this updated message?

**Comment by yukishilo** [comment]
Heads up: I got the dreaded "The dependency graph contained a cycle" when I named cartfile with a lowercase c.

**Comment by DerFlash** [comment]
> As a heads up, I've found that this error can also occur when the `Cartfile.resolved` is manually edited into the following state:
> 
> * Dependency `A` updated by hand to a new version in the `Cartfile.resolved`
> * The new version of the `A` dependency now depends on `B`, which it did not previously
> * The user that manually edited the Cartfile.resolved did not include the new version of `B` in their edit of the `Cartfile.resolved`
> * When resolving the dependency graph, carthage finds dependency `A` and `B` both need to be built
> * Since `B` is not passed into the topological sort as a node of the dependency graph (only as a relationship, since it is not in the `Cartfile.resolved`), it is recognized by the algorithm as a dependency cycle
> 
> My recommendation would be to add an extra error to the output in this scenario, along the lines of:
> 
> > The dependency graph either:
> > 
> > * Contained a cycle
> > * Was manually modified to be in an invalid state. Try retrying after performing a `carthage update`.
> 
> Perhaps we can reopen #1335 with this updated message?

I had the exact same error today with the latest Carthage version, took me some time to realize because of the misleading error message about some dependency cycle, which isn't there :-(

Easy scenario:
A → B

We just added a new dependency C to B, created the commit and referenced the new version of B in the Cartfile of A. For some reason we didn't use "carthage update" on A and instead just changed the dependency for B in Cartfile and Cartfile.resolved of A :-/
So the whole thing was just missing the reference of C in Cartfile.resolved of A...

Easy problem, but finding it because of the missleading error message was kind of hard.

Maybe this could also explain some findings in #1986 @blender ?

Kind regards
Björn

**Comment by davisford** [comment]
I spent a full day on this issue -- maddening.  Then I switched it to `Carthage++` and all my problems went away.

https://youtu.be/21nbRGpy3xM

```
brew uninstall --force carthage
brew tap nsoperations/formulas
brew install -s nsoperations/formulas/carthage
carthage update --platform ios
```

https://github.com/nsoperations/Carthage
