### ISSUE TITLE
Bad credentials error when trying to build a static library

### ISSUE THREAD

**Issue by Isuru-Nanayakkara** [Carthage/Carthage#1338]
Since most static libraries are supported by Carthage out of the box, I'm trying to build this library, [CardFlight](https://github.com/CardFlight/cardflight-ios) via Carthage. But running `carthage update --platform iOS` gets me a **bad credentials** error.

I tried this [solution](http://stackoverflow.com/a/35968450/1077789) but it didn't work either. Here's my setup.

* `carthage version`: 0.16.2
* `xcodebuild -version`: Xcode 7.3 Build version 7D175
* Are you using `--no-build`? No
* Are you using `--no-use-binaries`? No
* Are you using `--use-submodules`? No

**Cartfile**
```
github "CardFlight/cardflight-ios"
```

**Carthage Output**
```
*** Fetching cardflight-ios
*** Skipped downloading cardflight-ios.framework binary due to the error:
	"Bad credentials"
*** Checking out cardflight-ios at "3.2.1"
*** xcodebuild output can be found in /var/folders/lt/3tpmxm9175d5qg_8hd4k0h040000gn/T/carthage-xcodebuild.3teFVV.log
```

But the created log file is also empty.

**Comment by mdiep** [comment]
Carthage doesn't actually support static libraries. It only supports dynamic frameworks. Frameworks need to have an Xcode project with a shared dynamic framework scheme. Then Carthage will build it.

The `Bad credentials` isn't affecting this, but it means that the GitHub.com credentials that Carthage loaded from `Git` aren't valid. That's innocuous in this case, but could prevent you from downloading prebuilt frameworks from GitHub Releases.

Carthage isn't reporting an error because the repository contains no Xcode projects at all. That's a bug: you should get an error. I've opened #1340 to track this.

**Comment by Isuru-Nanayakkara** [comment]
Oh I see. Thanks for the detailed explanation.

**Comment by Isuru-Nanayakkara** [comment]
Btw I realized why I might be getting Bad Credentials message. I recently changed my Github password. Do I need to update it within Carthage somehow? If so, can you please tell me how?

**Comment by monica-futuristic** [comment]
I have a new Apple M1, I have been trying from a long time to update the Carthage. It is displaying me this issue everytime
Skipped downloading RxSwift binary due to the error:
	"Bad credentials"
