### ISSUE TITLE
Better integration with Travis CI

### ISSUE THREAD

**Issue by BanzaiMan** [Carthage/Carthage#1403]
Hello. I work with Travis CI. Our users have shown interest in better Carthage support, and I would like your help to make it a reality.

There are a couple of components to this that I need help with.
1. How to tell if a repository is set up for Carthage
2. What commands to run by default during various build phases.
3. What directories to cache

From the first read through of https://github.com/Carthage/Carthage#use-travis-ci-to-upload-your-tagged-prebuild-frameworks, I see that:
1. The existence of the file `Cartfile` signals that the repository should use Carthage
2. This is where I need help on. The document shows an example configuration, but they all happen in customized phases. They could be moved to other phases if needed.
3. Either
   - `Carthage`, or
   - `Carthage/Checkouts` and `Carthage/Build`, if there are directories under `Carthage` that should not be cached.

Am I on the right track? I'd appreciate any help you can provide.

Thank you.

**Comment by mdiep** [comment]
> Hello. I work with Travis CI. Our users have shown interest in better Carthage support, and I would like your help to make it a reality.

That's great! I'd love to help with that.

> The existence of the file Cartfile signals that the repository should use Carthage

Yes, but you might be more interested in `Cartfile.resolved`. That should also help you invalidate the cache because it lists what's actually built. There's more information about that [here](https://github.com/Carthage/Carthage/blob/master/Documentation/Artifacts.md).

> What commands to run by default during various build phases.

You'd want to run `carthage bootstrap`. There are a lot of options that enable different workflows (`--no-binaries`, `--use-submodules`, `--no-build`, `--platform <PLATFORM_NAME>`, etc.), but caching only makes sense if you're actually building with Carthage, so the default options should work pretty well. Still, you may want to make the options configurable.

> What directories to cache

I think you could cache all of `Carthage`. When building with Carthage, `Carthage/Build` is probably all that's necessary, but `Carthage/Checkouts` will probably improve compatibility and there shouldn't be much more work.

I'm happy to answer other questions you have. Travis CI has been a huge help with open source software, so I'm definitely a fan.

**Comment by guidomb** [comment]
I use TravisCI in all our company projects. I've automated everything related with bootstrapping the project for TravisCI using [this](https://github.com/guidomb/ios-scripts) scripts and I also made a [tool](https://github.com/guidomb/carthage_cache) to cache Carthage builds and share the artifacts with the team and CI. You can see a working example [here](https://github.com/wolox/ios-base-project). I don't know what you have in mind but better integration with Travis is always good. Currently my only problem with Travis is the build time.

**Comment by Hamuko** [comment]
Does Carthage actually benefit at all from caching `Carthage`? Because I see similar run times for `carthage bootstrap` regardless of the existence of `Carthage` for grabbing Alamofire and Realm for a project.

The bigger issue I see with using Travis CI and Carthage together is the fact that you cannot download ready binaries from Github to save yourself a lot of time, since it seems to fail with _"Maximum number of login attempts exceeded. Please try again later."_

**Comment by mdiep** [comment]
`carthage bootstrap` will currently take just as long if `Carthage` is cached (#1222), but if you have `Carthage`, then you potentially don't need to run `carthage bootstrap`.

**Comment by Hamuko** [comment]
But wouldn't you run `carthage bootstrap` with every new CI build to make sure you have all of the project dependencies, not just the ones that might be cached?

**Comment by mdiep** [comment]
Not if a change to `Cartfile.resolved` invalidates the cache.

**Comment by dcaunt** [comment]
@Hamuko there's a description of how one might cache Carthage products [here](https://robots.thoughtbot.com/caching-carthage-con-circleci) and you may also find [this bash script & tool](https://github.com/YPlan/CartfileDiff/#faster-carthage-bootstrap) useful
