### ISSUE TITLE
Copy frameworks only when needed

### ISSUE THREAD

**Issue by leoneparise** [Carthage/Carthage#1635]
Today Carthage copy frameworks on every build. It's unnecessary and increases the build/installation time a lot.

The user @lvillani provided a python script to address this problem. It solves two problems here, you don't need to pass all frameworks needed to be copied and copy only when it's needed.

Here is his repo: https://github.com/lvillani/carthage-copy-frameworks

What do you think? Can this be include as a feature inside Carthage?

**Comment by mdiep** [comment]
I think this part is would not be acceptable for us:

> Frameworks are not copied over and over again. This means that updated dependencies might not be picked up until you perform a clean build.

But a PR that made it so not all frameworks needed to be passed would certainly be welcome!

**Comment by lvillani** [comment]
I could build a mechanism to check whether frameworks changed between builds by using e.g. checksums but a) I'm not doing much iOS development these days (which means that I'm not going to do it) and b) I would strongly prefer to see what "carthage-copy-frameworks" does, but within Carthage itself, so that I can throw carthage-copy-frameworks in the trash :)

**Comment by ikesyo** [comment]
Closing this in favor of #1810 and #1841.
