### ISSUE TITLE
Submodules break Carthage symlink

### ISSUE THREAD

**Issue by bolismauro** [Carthage/Carthage#1700]
I'm not sure whether this intended or (most likely) I'm doing something wrong.

I have a project A that has a script `run.sh`.

Then I have a project B that has A as dependency and uses `run.sh`. B has a `run phase` with something like this
`${SRCROOT}/Carthage/Checkout/A/run.sh`

When I use B in a third project, C, the path is wrong.
It used to work in the past, when we didn't use submodules, thanks to a `Carthage` symlink that Carthage creates in `Checkout/B`.

Is it intentional that the symlinks are not created anymore?
Is there a way to avoid this?

(I'm not pushing the submodules in `B`. We had troubles with #135 and we eventually added that folder in the gitignore file as workaround. Is it related?)

Thanks!

**Comment by mdiep** [comment]
It is intentional that symlinks are not created in projects that use Carthage submodules. But we may be missing logic in projects inside of those.

So if

1. you have C that uses B that uses A
2. C uses submodules for B
3. B doesn't use submodules for A

Then B maybe should have a symlink for A but doesn't. Is that the case you're hitting?

I think the trouble is that creating a symlink for A in B will make B dirty in C. That's undesirable. 🤔

**Comment by bolismauro** [comment]
I think the problem is that `B` is using submodules for `A` for it doesn't have the git submodules tracked in git
