### ISSUE TITLE
Workflow: Working on dependencies during development 

### ISSUE THREAD

**Issue by opfeffer** [Carthage/Carthage#1745]
* `carthage version`: 0.18.1
* `xcodebuild -version`: Version 8.2.1 (8C1002)
* Are you using `--no-build`? no
* Are you using `--no-use-binaries`? no
* Are you using `--use-submodules`? yes

I've searched the documentation and issues for this question and figured I'd ask again, despite running the risk of asking the n-th time. Sorry in advance!

I'm looking for the carthage-recommended workflow of working on a main app and one of its dependencies at the same time. I've carefully reviewed the `README.md` and specifically #688 (and one of its comments https://github.com/Carthage/Carthage/issues/688#issuecomment-219410485).

Here's my rough setup:

```
     MainApp.xcodeproj
          |_ MyOwnFramework
               |_ Some3rdPartyLib1
               |_ Some3rdPartyLib2
```

Now, I've read all about the linking all dependencies to the main app, not nesting dependencies etc. I've set up MyOwnFramework similarly to how [ReactiveCocoa](https://github.com/ReactiveCocoa/ReactiveCocoa) structured theirs. There's a `.xcodeproj` with a shared scheme and a `.xcorkspace` that includes all its dependencies to allow it to build itself. So far so good.

Now, in my `MainApp/Cartfile` I reference my framework, and install via `carthage update --use-submodules --platform iOS`.

Here are my questions:
1) When trying to create a `.xcworkspace` in the MainApp repo holding both `MainApp.xcodeproj` and `Carthage/Checkouts/MyOwnFramework.xcodeproj` it won't build complaining "Cant find Some3rdPartyLib1" module in `MyOwnFramework/File.swift`. That the wrong approach?

2) Additionally, I tried [Automatically rebuilding dependencies ](https://github.com/Carthage/Carthage#automatically-rebuilding-dependencies), with the following command:

```
     /usr/local/bin/carthage build MyOwnFramework --platform iOS --project-directory "$SRCROOT"
```

with the intent to avoid rebuilding all the 3rd party dependencies (which won't change!) over and over again. However, I observed that Carthage appears to be building the scheme from `MyOwnFramework.xcworkspace` which as part of its build phase also rebuilds all the 3rd party dependencies ... again. That prolongs build times significantly, especially if only a single file changed. My setup looks very similar to what ReactiveCocoa's looks like with ReactiveSwift and Result and when running the above command on ReactiveCoca, it also appeared to rebuild its dependencies. Is there something I can do to avoid rebuilding libs that haven't changed?

Thanks for your time & help!

**Comment by mdiep** [comment]
You should either do (1) or do (2).

(2) will probably result in unnecessary building, as you've discovered. So (1) is probably the better approach.

It sounds like `MyOwnFramework` needs to have its framework search path adjusted or should follow the same submodule-, project-based approach.

**Comment by opfeffer** [comment]
Thanks @mdiep!

Just to clarify. Would I specify relative search paths for both scenarios?
1) standalone framework development in `MyOwnFramework.xcworkspace`, eg. `Carthage/Build`
and
2) nested development from within `MainApp`'s `Carthage/Checkouts` folder, eg. `../Build`

**Comment by mdiep** [comment]
A target needs search paths if it's not building its dependencies through a workspace.

**Comment by fruitcoder** [comment]
I have almost the exact same scenario with one exception: I want to add `MyOwnFramework` as a submodule myself (because of #426) and then add the `Some3rdPartyLib1` to my `MainApp`'s `Cartfile`. `MyOwnFramework` project is setup to build the targets (iOS, macOS, tvOS, watchOS) and is embedded in a workspace next (sibling) to `Some3rdPartyLib1` (in Cartfile, added as submodule through `carthage update --use-submodules`) , where the tests run fine. 
Linking the workspace `Some3rdPartyLib1` framework against `MyOwnFramework` gives it the Framework Search Path: `$(PROJECT_DIR)/Carthage/Checkouts/KeychainAccess/Lib/build/Debug`.

Copying `MyOwnFramework.xcodeproject` into `MainApp` (as a child) doesn't automatically setup the connection to the `Some3rdPartyLib1`. This may be because `MainApp` is not in the same directory as `MyOwnFramework`. My file structure is like this:
```
     App
          |_ MainApp.xcodeproj
          ...
     Cartfile (with Some3rdPartyLib1)
     Carthage
          |_ Build
               |_ iOS
                   Some3rdPartyLib1.framework
     Submodules
          |_ MyOwnFramework
                |_ MyOwnFramework.xcodeproject
                |_ MyOwnFramework.xcworkspace
                |_ Cartfile (with Some3rdPartyLib1)
                ...
     ...

```

while my project structure looks like this (NO workspace for `MainApp`)
```
     MainApp.xcodeproj
          |_ MyOwnFramework.xcodeproj
```

To make `MyOwnFramework` find the dependency I have to manually add `$(PROJECT_DIR)/../../../Carthage/Build` (recursive) to `MyOwnFramework`'s Framework Search Paths. Am I missing something or is there a way for `MyOwnFramework` to automatically find the framework in  `MainApp`? This way I have to commit this hardcoded search path, which is fine for me now, but it feels like I'm doing something wrong.
