### ISSUE TITLE
Question: Why can't Carthage use pre-build frameworks from the git repository vs the release?

### ISSUE THREAD

**Issue by samjarman** [Carthage/Carthage#1770]
* `carthage version`: 
Latest
* `xcodebuild -version`: 
Xcode 8.2
Build version 8C38
* Are you using `--no-build`?
No
* Are you using `--no-use-binaries`?
No
* Are you using `--use-submodules`?
No

**Cartfile**
github "theCompany/company-ios-sdk-XXX" (Private repository)

**Carthage Output**
Dependency "company-ios-sdk-XXX" has no shared framework schemes for any of the platforms: iOS

Hey Team,
This works if I attach the release as company.framework.zip to the release as a binary, but for CD, I'd have to write something with the Github API... why can't I just have company.framework.zip in the repository and have Carthage find that? Or can this really be done? Or can it not be done for X, Y, Z reasons? Would you be open to a PR fixing this? _That other package manager_ allows this ;)

**Comment by dcaunt** [comment]
Firstly, you might be interested to know that automating GitHub releases with CI is not much work, if you are [using Travis](https://github.com/Carthage/Carthage#use-travis-ci-to-upload-your-tagged-prebuild-frameworks).

Since 0.19 Carthage supports 'binary only' releases. You can read more [here](https://github.com/Carthage/Carthage/blob/master/Documentation/Artifacts.md#binary-only-frameworks) and [here](https://github.com/Carthage/Carthage/blob/master/Documentation/Artifacts.md#binary-project-specification). This should support your use case.

**Comment by mdiep** [comment]
Storing binaries inside a git project isn't a great solution, IMO.

But you should be able to use the new binary JSON support to do this. You could put the JSON in the repo and point it to the files in the repo.
