### ISSUE TITLE
--cache-builds forces build of downloaded binary frameworks in some cases

### ISSUE THREAD

**Issue by scottrhoyt** [Carthage/Carthage#1802]
* `carthage version`: 0.20.0
* `xcodebuild -version`: 8.2.1
* Are you using `--no-build`? no
* Are you using `--no-use-binaries`? no
* Are you using `--use-submodules`? no

**Cartfile**
```
github "SwiftyJSON/SwiftyJSON" "2.4.0"
```

**Carthage Output**
```
*** Downloading SwiftyJSON.framework binary at "2.4.0"
*** xcodebuild output can be found in /var/folders/kk/vhmt6xwd5f17hfq_zz_lbnth0000gn/T/carthage-xcodebuild.CHOsXk.log
*** Invalid cache found for SwiftyJSON, rebuilding with all downstream dependencies
*** Building scheme "SwiftyJSON iOS" in SwiftyJSON.xcworkspace
```

Running `TOOLCHAINS=com.apple.dt.toolchain.Swift_2_3 carthage update --platform ios --cache-builds` repeatedly always detects an invalid cache for `SwiftyJSON` and always forces a rebuild even though the binary is being downloaded.

**Comment by ikesyo** [comment]
You may be hitting #1585 (and #1509). But now #1755 has been merged, so we could/should revisit that.

**Comment by BobElDevil** [comment]
So what's happening here is that there's a SwiftyJSON checkout folder that already exists, so it gets pulled into the list of items it should build. If you `rm -r Carthage/Checkouts/SwiftyJSON` and re-run that same command, it won't rebuild anything (though it still erroneously spits out an 'Invalid cache' message).

Note that this doesn't appear to be specific to `--cache-builds`. If you drop --cache-builds from the command, but have a Checkouts/SwiftyJSON folder sitting around it will download the binary _and_ build it, every time. 

I think this boils down to an assumption in carthage that if we downloaded a binary, we didn't do a checkout. Which falls apart if a checkout has been performed previously (due to --no-use-binaries, or a previous version without a binary release). 

Note that this is related to #1466, in that when solving 1466 we would have to solve this problem as well, since in general we don't want to build if we just downloaded a binary. 

The solution for the --cache-builds case could be that we generate a version file immediately after downloading for a release, essentially pre-marking it as valid. However that doesn't handle the case when '--cache-builds' isn't passed. That would have to essentially check the cache even when the flag is off, because we know it's a binary download not just a previously built framework. Maybe we could add a flag to the version file to signify that.

**Comment by scottrhoyt** [comment]
Thanks for the analysis @BobElDevil! That indeed does seem to be the case. I'm going to go ahead and close this issue in light of #1466 and this being not related to `--cache-builds`. We might want to open up an issue tracking the cache status output for downloaded binaries?
