### ISSUE TITLE
Feature: produce .version file for current framework  —no-skip-current

### ISSUE THREAD

**Issue by netbe** [Carthage/Carthage#1846]
* `carthage version`: 0.20.1
* `xcodebuild -version`: Xcode 8.2.1\nBuild version 8C1002
* Are you using `--no-build`? no
* Are you using `--no-use-binaries`?  no
* Are you using `--use-submodules`? no
* Are you using `--cache-builds`? yes

**Actual:**
While doing `carthage build —cache-builds —no-skip-current` the `.version` is not produced for the current framework.

**Expected:**
It would be great if it was as we have jobs that build frameworks and cached the results.

**Comment by erichoracek** [comment]
I've created #1850 to do something like this—the change in that PR causes a `.CurrentBuild.version` file to be created when `--no-skip-current` is specified during a `carthage build`. However, since `--cache-builds` does not cache builds in a global place (only in the `Carthage/Build` folder in the working directory), this may not be precisely what you're asking for.

#1850 would only helpful if you use `--cache-builds` in combination with prebuilt frameworks attached to Github releases, as discussed in #1839.

The reason that the file is named `.CurrentBuild.version` is because the repository name is not known at the time of `carthage build` (same goes for the `commitish` field), this is only populated when the artifact produced by `carthage archive` is unpacked as part of a checkout.

**Comment by netbe** [comment]
@erichoracek how can I try that? compile from source your branch ? 

I guess once done I can manually rename the .CurrentBuild.version to whatever .framework.version and add the commitish myself.

**Comment by blender** [comment]
@erichoracek according to what I read in the other issues and pull request that you mentioned this should be enough for others (*[cough](https://github.com/blender/Rome)*) to build upon

**Comment by erichoracek** [comment]
@netbe Building from source on my branch should work for trying it out. However note that it may change as part of code review (or it may be rejected outright).
