### ISSUE TITLE
Specify cache directory option

### ISSUE THREAD

**Issue by ekimia** [Carthage/Carthage#1920]
Especially for use with CI, having a central location for cached frameworks (ideally with some sort of expiry) would be amazing.

* `carthage version`: 
* `xcodebuild -version`: 
* Are you using `--no-build`? 
* Are you using `--no-use-binaries`? 
* Are you using `--use-submodules`? 
* Are you using `--cache-builds`? 

**Cartfile**
```
<YOUR CARTFILE>
```

**Carthage Output**
```
<OUTPUT>
```

**Comment by blender** [comment]
@ekimia I made https://github.com/blender/Rome that probably meets your needs.

**Comment by ekimia** [comment]
@blender very cool, what are the main perks of using this vs [carthage_cache](https://github.com/guidomb/carthage_cache)?

**Comment by blender** [comment]
- Cache **just** what you need
  - Per dependency cache keys derived from `Cartfile.resolved` instead of caching the entire build folder
  - Changing one library won't invalidate your cache
- Cache redundancy
  - local folder
  - Amazon S3
- Probe cache for presence of single key
- Blacklist some keys
- Selective Download/Upload
  - 1,2,3... all frameworks
- Per platform cache
  - iOS, tvOS, MacOS, watchOS

Cached artifacts

- Frameworks
- dSYMs
- Carthage `.version` files

and many more features being developed among which
- Current framework upload
- Auto generation of Romefile
- Google Cloud Storage, Azure Storage

**Comment by peterromfeldhk** [comment]
I have in one CI job multiple carthage steps. I would love to be able to do something like:
```
- export CARTHAGE_CACHE=$(tempdir -d)
- carthage bootstrap --no-use-binaries --platform iOS --cache-builds
- carthage bootstrap --no-use-binaries --platform iOS --cache-builds --project-directory AnotherOne
- carthage bootstrap --no-use-binaries --platform iOS --cache-builds --project-directory ...
```
