### ISSUE TITLE
Checkouts are moved to trash when using --cache-builds and valid cache is found

### ISSUE THREAD

**Issue by juraj-blahunka** [Carthage/Carthage#1969]
* `carthage version`: 0.23.0
* `xcodebuild -version`: Xcode 8.3.2
Build version 8E2002
* Are you using `--no-build`? no
* Are you using `--no-use-binaries`? no
* Are you using `--use-submodules`? no
* Are you using `--cache-builds`? yes

**Cartfile**
```
github "card-io/card.io-iOS-source" == 5.4.1
github "CocoaLumberjack/CocoaLumberjack" == 3.1.0
github "airbnb/lottie-ios" == 1.5.1
...
```

**Carthage Output**
```
[10:53:03]: ▸ *** Checking out lottie-ios at "1.5.1"
[10:53:03]: ▸ *** Checking out CocoaLumberjack at "3.1.0"
[10:53:04]: ▸ *** Checking out card.io-iOS-source at "iOS_5.4.1"
"aec802ba2c2f524f8a47708aa6f714a48be73f49"
[10:53:12]: ▸ *** xcodebuild output can be found in /var/folders/bn/y5hxkvm9625gwfdtdl4f527h0000gp/T/carthage-xcodebuild.8OuaPI.log
[10:53:13]: ▸ *** Valid cache found for card.io-iOS-source, skipping build
[10:53:13]: ▸ *** Valid cache found for CocoaLumberjack, skipping build
[10:53:13]: ▸ *** Valid cache found for lottie-ios, skipping build
...
```

Bootstrapping carthage with --cache-builds on a CI machine fills up disk space pretty quickly, since all checkouts, for which a valid cache is found, are moved to trash.

**Comment by BobElDevil** [comment]
This actually has nothing to do with cache-builds. Rather, we've always trashed the checkout folder when there was a binary release found for that repo. However I believe due to recent changes as part of #1760, we now trash it `on(completed:)` for _all_ dependencies, instead of just ones that have binary releases. This was implicitly avoided previously because it was a `flatMap` on the unzipped directory, so if it had no binary, no directory got produced by the signal.

So first thing we should do is fix it to make sure we don't touch the checkout folder if there's not a binary release associated with it. But secondly, i'm not entirely clear why we're 'trashing' the checkout instead of simply removing it. 

A simple workaround for now is to pass `--no-use-binaries`, even if you don't have any binaries to worry about, as it will cause carthage to bypass this codepath.

**Comment by BobElDevil** [comment]
In fact looking deeper at this, the frameworks that _do_ have binaries aren't getting trashed, because the signal in question is getting disposed of before we are complete. So we get an 'interrupted' event instead of a 'completed' event 🤦‍♂️ , so we're doing exactly the opposite of what we intended. Seeing if I can un-reverse this
