### ISSUE TITLE
Unexpected fetch on build command

### ISSUE THREAD

**Issue by beseder42** [Carthage/Carthage#2034]
* `carthage version`: 0.23.0
* `xcodebuild -version`: 8.3.3
* Are you using `--no-build`? no
* Are you using `--no-use-binaries`? no
* Are you using `--use-submodules`? no
* Are you using `--cache-builds`? yes

We are committing the checkout folder with our app to use it with CI. The CI builds with 

`build --cache-builds --platform iOS`

Unexpected: Carthage performs a fetch for some dependencies before the build. That breaks the CI for dependencies that need credentials - since we don't supply them on CI at the moment.

We would not expect `build` to perform a fetch. 

Is the fetch expected - and why? How could we ensure that build does not perform a fetch?

**Comment by BobElDevil** [comment]
Currently we are performing a fetch because we are reading the Cartfile from the git cache (and we fetch/clone if the git cache isn't there) in order to figure out the order to perform builds. It seems we could optimize this by reading the Cartfile from the one in the 'Checkouts' folder if we're in the build stage. This would avoid unneeded fetches, since we know we already checked out everything to the commit we expect.

The one thing that throws a kink in this are dependencies with binary releases. Currently we throw away the checkout folder of any dependency that has a binary release. This is because our build logic at the moment blindly builds anything it finds in that folder. #1466 Discusses this issue.

Until that is solved, then we can't 100% guarantee no fetches would occur. However we could probably implement this by having it look at the checkout folder first, and if it doesn't exist do the current fetch behavior. Then if you don't use binaries it works as expected, but if you do, it'll fall back to fetches (at least until 1466 is fixed)

**Comment by beseder42** [comment]
That would be great and meet our use case!

**Comment by ikesyo** [comment]
We already skip unnecessary fetches on `cloneOrFetch` in `Project.swift` except that if a dependency is specified with a branch.

https://github.com/Carthage/Carthage/blob/e6629d00a7911c854ec860b5453532cb67d5fa1d/Source/CarthageKit/Project.swift#L1218-L1234

So fetching for a branch is expected behavior I think.
