### ISSUE TITLE
Warn about project find ambiguity

### ISSUE THREAD

**Issue by keithduncan** [Carthage/Carthage#213]
If there’s more than one project / workspace found at a given enumeration level Carthage should warn that only one will used and that which one used is undefined (determined by the order that the file system yields dir entries).

**Comment by rogernolan** [comment]
:+1: I would also like the ability to override the default behaviour and force Carthage to build a specific project/target to save having to fork/modify every project one needs Carthage to build.

**Comment by jspahrsummers** [comment]
@rogernolan That won't work easily for dependencies (especially transitive ones).

**Comment by rogernolan** [comment]
Not sure I understand what you mean but without it, Carthage must require all projects to layout in a "Carthage friendly" way which is going to be a big problem for adoption.

I would love to use Carthage rather than Pods but I keep hitting problems because Carthage isn't flexible enough to cope with less that perfect dependencies. I'm much happier controlling this through a more complex cart file than having a half mix of external/internal builds and other assorted special cases.

**Comment by jspahrsummers** [comment]
I'm suggesting that it's non-trivial to specify this kind of information outside of the project itself.

Consider two projects, A and B, that both depend on C, which has been set up in a way that isn't Carthage compatible by default. If A specifies one particular project/scheme for building, and B happens to specify another, who wins? What should be the behavior?

It's far simpler to resolve these concerns within the dependency itself, by asking for a reasonable (IMO) standard configuration that automated tools can understand.

**Comment by atheken** [comment]
I'd like to second @rogernolan's request. Being able to look at a repo and request a specific scheme be built from a Cartfile makes many more dependencies available without trying to get all of those framework authors to "adopt carthage."

That said, I do recognize the issue of two different dependencies needing to be built differently, but isn't this inherently an issue anyway? 

Does adding the feature to explicitly declare the scheme you wish to build make the sub-dependency problem worse, or is it neutral?

At an absolute minimum, it would be helpful if Carthage could report when the ambiguity occurs, so that it can be reported to repo owners.

**Comment by mdiep** [comment]
This isn't relevant anymore. Carthage now builds all shared dynamic framework schemes in the project.
