### ISSUE TITLE
Framework Dependencies Cause Multiple Builds

### ISSUE THREAD

**Issue by fostah** [Carthage/Carthage#2141]
I'm looking for some advice on the following situation. I have two frameworks, let's call them framework A and framework B. In my repository I have two projects, one for A and one for B. B has a dependency on A. So in B's project I specify a target dependency on A and I link to A.framework. 

Both A and B have Shared Targets so that they can be brought in another project with Carthage. What I'm seeing when I run carthage update with a Cartfile that references my repository is that framework A builds first, then framework B. However, as part of building framework B, framework A is built again. I'm assuming the Target Dependency didn't find framework A and required it to build.

Is there away around this? Maybe a different repository structure or a different way to define a dependency between two of my own framework?

**Comment by blender** [comment]
--cache-builds

**Comment by BobElDevil** [comment]
So --cache-builds wouldn't help in this situation, as you have 2 different schemes building 'A'. The A scheme, and then the B scheme (which builds A again). You have a couple of options:
- Don't 'share' the A framework scheme, since you're relying on B to build it for you. The problem with this is usually un-shared schemes are .gitignore'd so if that's the case for you, it wouldn't be versioned anymore, if that's an issue
- Remove the target dependency from project B. Instead, create a new workspace, with both projects in it, and create a new shared scheme that builds both frameworks, in the order needed. Carthage will prefer workspace schemes over project schemes, so that scheme _should_ take precedence, and build each framework once.
- Split A into it's own repo, and point B at it with a Cartfile, so A becomes a carthage tracked dependency and gets all the benefits therein. Obviously a pretty drastic change, but may make sense if you see these 2 frameworks as being contributed to separately.

**Comment by blender** [comment]
@fostah __project target dependency != carthage dependency__. Carthage manages dependencies viaa Cartfile. Unless you have a Cartfile in B carthage has no clue B depends on A.

Your problem is that in B you have A as target dependency, so you must have A's project inside B's project.

Carthage builds A, then builds B. Carthage knows nothing about the target dependencies  of B  so it will just build your B scheme, which requires A to be built again. Xcode knows nothing about what Carthage is doing and were the build artifacts are so it will build A again.

Like @BobElDevil said

>Split A into it's own repo, and point B at it with a Cartfile, so A becomes a carthage tracked dependency and gets all the benefits therein. Obviously a pretty drastic change, but may make sense if you see these 2 frameworks as being contributed to separately.

Then --cache-builds will help when rebuilding B

**Comment by fostah** [comment]
Thanks, @BobElDevil and @blender 

@BobElDevil's second bullet point addresses my issue, except you can't use a workspace because Carthage doesn't seem to pick up workspace schemes (note that I'm running 0.24.0, incase that feature was introduced in 0.25.0 or later). So I created a separate project instead (I'm going to refer to this as the SDK project). I deleted all the default stuff for the SDK project, including the scheme and target. I created a new scheme with no target. Then I dragged in all the framework projects to the SDK project and had the scheme build each framework target.

Note that if you build all the framework targets with the SDK project's default scheme, which is associated with a default target for the project, only the default target's product is added to the Carthage/Build directory.

Thanks again for the help.
