### ISSUE TITLE
Dependency Resolution question

### ISSUE THREAD

**Issue by lucas34** [Carthage/Carthage#2309]
* `carthage version`: 27
* `xcodebuild -version`: Xcode 9.2 (Build version 9C40b)
* Are you using `--no-build`? NO
* Are you using `--no-use-binaries`? NO
* Are you using `--use-submodules`? NO
* Are you using `--cache-builds`? YES

**Cartfile**
```
github "ReactiveX/RxSwift"
github "RxSwiftCommunity/RxSwiftExt"
```

**Cartfile Resolved**
```
github "ReactiveX/RxSwift" "4.1.0"
github "RxSwiftCommunity/RxSwiftExt" "3.1.0"
```

Current latest version of RxSwift is 4.1.0. When I updated with 'carthage update --cache-builds --platform iOS' carthage downloaded the pre-build framework and updated the cartfile.Resolved from 4.0.0 to 4.1.0.
The problem is, I also have a Dependency to RxSwiftExt which has this following cartfile.

**RxSwiftExt Cartfile**
```
github "ReactiveX/RxSwift" "4.0.0"
```

There is now an inconsistency in the cartfile. It depends on RxSwift 4.1.0 and on RxSwift 4.0.0 (Through) RxSwiftExt. This makes me a bit confuse about which version is now used.
I guess my Cartfile.Resolved should only update to RxSwift 4.1 when all dependencies also support it (?)

**Comment by mdiep** [comment]
The `Cartfile` for RxSwiftExt should be something like:

```
github "ReactiveX/RxSwift" == 4.0.0
```

(Or probably `~>` instead of `==`, but then you'd see the same behavior you're seeing here.)

You're specifying a git ref of `4.0.0`, which could be a branch or a tag, and isn't subject to semantic versioning. If you want to add a semantic versioning constraint, you need to specify your dependency with semantic versioning.

**Comment by lucas34** [comment]
Thanks for the clarification
