### ISSUE TITLE
Carthage freezes forever with certain version numbers

### ISSUE THREAD

**Issue by mlfarrell** [Carthage/Carthage#2323]
* `carthage version`:  0.27
* `xcodebuild -version`: 
* Are you using `--no-build`? 
* Are you using `--no-use-binaries`? 
* Are you using `--use-submodules`? 
* Are you using `--cache-builds`? 

**Cartfile**
```
github "BranchMetrics/ios-branch-deep-linking" ~> 0.22.5
```
github "BranchMetrics/ios-branch-deep-linking" ~> 0.22.5
**Carthage Output**
```
Nothing
```

**Comment by mlfarrell** [comment]
Now it's just freezing randomly altogether.  Seems to be infinitely recursing at random.  Dammit.  This is not the day for this to be happening.  Please get off of "reactive" programming.  This is what happens when using these programming styles..

**Comment by blender** [comment]
@mlfarrell 

I have checked with your Cartfile and everything works.

```
$ carthage bootstrap
*** No Cartfile.resolved found, updating dependencies
*** Fetching ios-branch-deep-linking
*** Downloading ios-branch-deep-linking.framework binary at "Release 0.22.5"
*** xcodebuild output can be found in /var/folders/pn/14183n6j2bz0s2_qlcqtg5_00000gn/T/carthage-xcodebuild.TgJq9h.log
```

I recommend you check your network settings or firewall.

**Comment by mlfarrell** [comment]
That is just a snippet.  The entire thing is larger.  Some urls removed for security (sorry, I can't post those repo links)

```
github "ReactiveX/RxSwift" ~> 3.2
github "RxSwiftCommunity/RxDataSources" ~> 1.0

github "testfairy/testfairy-carthage"

github "Alamofire/Alamofire" ~> 4.4
github "Alamofire/AlamofireImage" ~> 3.2

github "SwiftyJSON/SwiftyJSON" ~> 3.1

github "aschuch/AwesomeCache" ~> 5.0

#until fabric gets their carthage act together
binary "https://raw.githubusercontent.com/Building42/Specs/master/Carthage/Fabric.json"
binary "https://raw.githubusercontent.com/Building42/Specs/master/Carthage/Crashlytics.json"

github "BranchMetrics/ios-branch-deep-linking"
github "stripe/stripe-ios" ~> 11.0

#covers all of AWS
github "aws/aws-sdk-ios" ~> 2.5

#broken - https://github.com/uservoice/uservoice-ios-sdk/issues/446
#github "uservoice/uservoice-ios-sdk"

github "SVProgressHUD/SVProgressHUD" ~> 2.0
github "TTTAttributedLabel/TTTAttributedLabel"
github "bryx-inc/BRYXBanner"
github "dzenbot/DZNEmptyDataSet"
github "xmartlabs/XLPagerTabStrip" ~> 7.0
github "hackiftekhar/IQKeyboardManager" ~> 4.0

github "dennisweissmann/DeviceKit" ~> 1.0

github "intercom/intercom-ios"

github "CocoaLumberjack/CocoaLumberjack"

github "openid/AppAuth-iOS" ~> 0.92
github "MortimerGoro/MGSwipeTableCell"

github "evsinev/BerTlv"
github "jsonmodel/jsonmodel" "master"
github "mixpanel/mixpanel-iphone" ~> 2.9.9

github "twilio/twilio-chat-ios" ~> 2.1
github "twilio/twilio-accessmanager-ios" ~> 1.0


# requires repo access
git "git@bitbucket.org:removed.git" "master"

### no mans land below, frameworks that don't officially support carthage ###
# none of these work properly anymore, we have no choice but to add these 
# manually until they support carthage (or better, we stop using them)
```

**Comment by blender** [comment]
First off, unless this is some development branch, I recommend you to specify versions in your dependencies. 

Your issue is that in one of these dependencies that uses Carthage, there is a clashing version required for some common dependency. I doubt this is in some public repo so check the Cartfile.resolved in your private repositories and look for incompatible versions of the same dependency.

**Comment by mlfarrell** [comment]
So you're saying the issue is most definitely caused by the contents of my private bitbucket.org repo?

**Comment by blender** [comment]
I'm saying that in one (or more) of these repos there is a Cartfile.resolved that wants one of these dependencies (or a transitive one) at a version which is incompatible (semantically) with what specified in some other Cartfile.resolved for the same dependency in another repo.

Example:

RepoA Cartfile.resolved
```
github "Alamofire/Alamofire" "2.2.0"
```

RepoB Cartfile.resolved
```
github "Alamofire/Alamofire" "3.2.0"
```

RepoC Cartfile
```
github "RepoA/RepoA"
github "RepoB/RepoB"
```

This will not work because one repo wants Alamofire at 2.0.0 and some other repo wants it at 3.0.0

**Comment by mlfarrell** [comment]
Thanks for the help sofar.  I don't suppose there's any way for me to easily find out which repos are responsible?  My client's dependency tree is a bit of a mess.

**Comment by blender** [comment]
No, unfortunately there is no easy way.  I suggest you patiently do by hand the same job carthage would do.

Otherwise, you can try to compile carthage and see for what repo the dependency resolved hangs.
Instructions are dead simple, see https://github.com/Carthage/Carthage/blob/master/CONTRIBUTING.md . You need Xcode 9.2

**Comment by mlfarrell** [comment]
Cool got it.  Appreciate the help.  One minor suggestion I may have on my end is some sort of dependency cycle detection within the next release.  Something along the lines of "hey, this node has been visited over 1000 times, we're probably in a cycle".

**Comment by blender** [comment]
I agree. Feel free to submit a PR :)

**Comment by werner77** [comment]
I implemented an alternative resolver in my fork (since I was having a lot of problems like yours as well). Could you try it out to see if the issues are fixed? The fork is here: https://github.com/werner77/Carthage

Run carthage update with the --fast-resolver option
