### ISSUE TITLE
Build with the null codesigning identity so a certificate is not required

### ISSUE THREAD

**Issue by pchatsu** [Carthage/Carthage#235]
I don't join iOS developer program yet, and only use iOS simulator.
I used `carthage update` , but failed and the build log said,

```
Check dependencies
Code Sign error: No code signing identities found: No valid signing identities (i.e. certificate and private key pair) matching the team ID “(null)” were found.
CodeSign error: code signing is required for product type 'Framework' in SDK 'iOS 8.1'
```

So I tried to regist the code sign with Xcode's suggestion, but it said "You need to add an apple ID account that is enrolled in Developer's program.".

Can't I use carthage without joining iOS developer program for `xcodebuild`?

**Comment by sebbean** [comment]
What about CI builds (Travis for instance)

I was hoping to use Carthage to pull in my private custom framework dependency. Works great locally, however breaks on Travis environment (presumably because of lack of code signing credentials)

Took me all day to track down this as the most likely culprit for this error:

```
carthage build --no-skip-current
*** xcodebuild output can be found in /var/folders/gw/_2jq29095y7b__wtby9dg_5h0000gn/T/carthage-xcodebuild.cnE6me.log
*** Building scheme "Gravy" in Gravy.xcodeproj
** BUILD FAILED **
```

Side note: It may be helpful to have a flag that tail's the xcodebuild log during build, as Travis doesnt allow you to go in and examine the file system as far as I'm aware - makes it a bit tricky to debug this error.

**Comment by jspahrsummers** [comment]
@sebbean You'll have to ensure that Travis imports a code signing identity. You can see how Carthage itself does it in the [`cibuild`](https://github.com/Carthage/Carthage/blob/12fb7881876b4987584e49d00befcd2a8b6b354d/script/cibuild#L29-L51) script.

> Side note: It may be helpful to have a flag that tail's the xcodebuild log during build, as Travis doesnt allow you to go in and examine the file system as far as I'm aware - makes it a bit tricky to debug this error.

Filed as https://github.com/Carthage/Carthage/issues/273.

**Comment by dwlnetnl** [comment]
I'd really like to option to build only for the simulator because I don't have a code signing identity yet. It keeps starting app developers from using Carthage.

**Comment by jspahrsummers** [comment]
@dwlnetnl Thanks for the suggestion! Unfortunately, that would add a significant amount of complexity. Right now, it's very clear that when Carthage builds for iOS, you'll get a universal framework that you can use in both device and simulator builds.

I'd like to keep that simplicity if possible. :relaxed:

**Comment by dwlnetnl** [comment]
@jspahrsummers You are absolutely right!

**Comment by abbeycode** [comment]
Any update on this or #281? I'm hitting this in Travis now

**Comment by drosenstark** [comment]
For those of us who got here from the Internet: try building only the platform you need. For iOS, for instance, use

`carthage build --platform iOS`

**Comment by midix** [comment]
Just curious, have Apple changed this? Because I just built `Release-iphoneos` "Cocoa Touch Framework" in XCode 8.2.1 (I used Build for profiling) with empty signing settings: http://i.imgur.com/S37J3HN.png  So, is it signed or not? Maybe it's just using my default XCode "iOS developer" signing? I do not have Provisioning profile.

**Comment by mdiep** [comment]
Yes, signing is not longer required when building a framework—and Carthage turns it off.
