### ISSUE TITLE
is this project supported?

### ISSUE THREAD

**Issue by jafara** [Carthage/Carthage#2466]
I see multiple issues being filed here with various problems and complaints online. Have considered switching from cocoapods but I dont see how this is any better? Is version 1.0 soon to be released?

is it a problem its written in swift with how frequently swift changes by Apple?

**Comment by blender** [comment]
Hi @jafara 

> is this project supported?

It's supported by volunteers, people using Carthage and why not by yourself too? It's [easy to get started](https://github.com/Carthage/Carthage/blob/master/CONTRIBUTING.md)! There is no one paying for development to be done on this project, I would say this is pretty standard open source. If you want to have a pulse on how active the project is, be my guest and [check the pull requests merged since the last release](https://github.com/Carthage/Carthage/compare/0.29.0...master). This is public information.

> Have considered switching from cocoapods but I dont see how this is any better?

If you are happy with Cocoapods I don't see a reason to switch. If you are not sure how Carthage is different from Cocoapods, please read here. https://github.com/Carthage/Carthage#differences-between-carthage-and-cocoapods

> I see multiple issues being filed here with various problems and complaints online.

I'm sure this is not the only project where you can see this.

> is it a problem its written in swift with how frequently swift changes by Apple?

Is it a problem to you?  Binaries don't stop working because a new version of Swift comes out.
