### ISSUE TITLE
Best practice for adding a Carthage dependency to my Carthage Framework

### ISSUE THREAD

**Issue by tunidev** [Carthage/Carthage#2583]
I'm developing a Framework named "MyFramework" which compatible with Carthage but I need "Alamofire" as dependency to my "MyFramework". 

1) What are all options to include "Alamofire" to my "MyFramework"  ?

2) What is the most recommended way ? 

3) Any real life example ? 

Thank you

**Comment by blender** [comment]
In "MyFramework" use a `Cartfile` and add Alamofire as a dependency. This dependency will be passed on to whatever project depends on "MyFramework"

**Comment by gaurav1981** [comment]
@blender 
can u confirm if we can use the copy-frameworks script on the added dependencies so that final framework can be used for app store submission as well?
I was trying to do the following steps in order to use custom framework for app-store submission:
1) Generate framework with normal approach as mentioned in Readme on carthage homepage
2) Tried running copy-framework script step to do the needful with output folder set to other than the default expected folder (was trying this as hit and trial)
intention of step 2 was to see if i can still use the script to do needful on the added dependencies.
3) copy the frameworks from step 2 location to the actual framework parth in the final target.
4) run the strip symbol script (copied from net) before archiving or so on the final custom framework.
I am currently using XCode 10 with carthage v0.30.1

**Comment by blender** [comment]
You just need to add `carthage copy-frameworks` to a custom run script phase with the list of inout and output file as specified in the quick start guide at point 8.

**Comment by gaurav1981** [comment]
> You just need to add `carthage copy-frameworks` to a custom run script phase with the list of inout and output file as specified in the quick start guide at point 8.

so `carthage copy-frameworks` this would take care of doing the needful for the main framework as well the other embedded frameworks, recursively?
