### ISSUE TITLE
Carthage hangs at build state – Mojave OS

### ISSUE THREAD

**Issue by YummyTastyCode** [Carthage/Carthage#2635]
carthage update --platform iOS --verbose

**Cartfile**

github "Alamofire/Alamofire" == 4.7.3

**Carthage Output**
The last output is 
```
Touch /Users/sla/Library/Caches/org.carthage.CarthageKit/DerivedData/10.1_10B61/Alamofire/4.7.3/Build/Intermediates.noindex/ArchiveIntermediates/Alamofire\ iOS/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/Alamofire.framework (in target: Alamofire iOS)
    cd /Users/<user>/Documents/ios/<app>/Acronis\ Mobile/Carthage/Checkouts/Alamofire
    /usr/bin/touch -c /Users/sla/Library/Caches/org.carthage.CarthageKit/DerivedData/10.1_10B61/Alamofire/4.7.3/Build/Intermediates.noindex/ArchiveIntermediates/Alamofire\ iOS/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/Alamofire.framework

 ARCHIVE SUCCEEDED
```

**Actual outcome**
It hangs

**Expected outcome**
```
/usr/bin/xcrun xcodebuild -workspace ..... 
```
have to be executed.

I really don't understand what happens.

**Comment by bradleyrzeller** [comment]
Were you able to fix this @YummyTastyCode ? I am hitting this as well, but only on CircleCI.

**Comment by ollieatkinson** [comment]
Also seeing this issue, again, only on CircleCI.

**Comment by bradleyrzeller** [comment]
@ollieatkinson I hate these types of answers but I did _several_ things to workaround this issue. Not sure what the real, underlying issue is. But the following at least let Circle be happy again...

* use Xcode 10.2.0 image on circle
* I'm using Fastlane, bumped it to 2.120.0
* Likely not related but disabled the Xcode's new build system.
* Migrated to swift 5

Hope this helps.

**Comment by mpaillet3821** [comment]
If it helps someone. We have a remote Mac mini that we use to run CI/CD jobs and I was having this same issue when seeing the logs on our GitHub actions execution.

Turns out in the Mac mini the system was asking user permission (with a popup) to install xcodetools latest updates. I accepted that and everything started working again. 

Not saying it was the exact issue you guys experienced but this might throw some light on it if someone else ends up here having this problem and hopefully be of help.
