### ISSUE TITLE
Finder window launches when build is finished

### ISSUE THREAD

**Issue by craigrouse** [Carthage/Carthage#2680]
* carthage install method: [ ] .pkg, [X] homebrew, [ ] source
* `which carthage`: /usr/local/bin/carthage
* `carthage version`: 
* `xcodebuild -version`: 10.1
* Are you using `--no-build`? No 
* Are you using `--no-use-binaries`? No
* Are you using `--use-submodules`? No
* Are you using `--cache-builds`? No
* Are you using `--new-resolver`? No

**Cartfile**
```
github "tealium/plcrashreporter"
```

**Carthage Output**
```
*** Fetching plcrashreporter
*** Checking out plcrashreporter at "1.3"
*** xcodebuild output can be found in /var/folders/y1/q1bs2vcj4hl0z21kb5nr961r0000gn/T/carthage-xcodebuild.tXXCgH.log
*** Building scheme "TealiumCrashReporteriOS" in CrashReporter.xcodeproj
```

**Actual outcome**
The project builds successfully - no issues there. The "problem" is that after the build succeeds, a Finder window opens in the `Carthage/Checkouts/plcrashreporter` directory.

I cannot figure out what's causing this. I've tried turning on verbose logging, but there were no clues in the logs. This only happens with this particular project. There are no scripts or anything in the project that would cause this issue, as far as I can see, and the issue doesn't happen if I build the scheme using Xcode or xcodebuild directly; only when using Carthage.

In the scheme of things, this is a minor, albeit annoying, issue. I've spent a while trying to investigate this, but haven't found any clues. Hoping that somebody else might be able to point me in the right direction!

Extra info: I own the repo in question (`tealium/plcrashreporter`).

**Expected outcome**
Carthage should **not** launch a Finder window after the build process is complete.

**Comment by mdiep** [comment]
Carthage definitely isn't doing this. 😕

**Comment by craigrouse** [comment]
@mdiep Thanks for the reply. I'm at a bit of a loss, as it only happens when building with Carthage. I agree it's very strange, but it is reproducible every time (on different machines).

**Comment by CocoaGoofy** [comment]
@mdiep This definitely is happening.  We have a Mac mini running a Xcode Server Bot that executes `carthage bootstrap --new-resolver`.  (This is Xcode 10.1 on macOS High Sierra.  The prebuilt dependencies Carthage is downloading were built with Xcode 10.0 so carthage must build all targets of each dependency.  

Well, after a single day the Mac mini's monitor is covered with tiled Finder windows.

![carthagefinderwindows](https://user-images.githubusercontent.com/30421036/51067611-c5578300-15c8-11e9-815c-5c48b7d7faed.jpg)

Like @craigrouse mentions, this only happens when carthage causes Xcode to build the dependency.

**Comment by mdiep** [comment]
<img width="905" alt="open" src="https://user-images.githubusercontent.com/1302/51068397-4f184800-15eb-11e9-8290-7ac8c2d633b0.png">

**Comment by craigrouse** [comment]
@mdiep now I feel stupid... sorry for wasting your time. Thanks for taking a look. I looked everywhere except there, and search didn't show anything up.
