### ISSUE TITLE
How can I use a (private) xcconfigs dependency?

### ISSUE THREAD

**Issue by akashivskyy** [Carthage/Carthage#278]
I included `jspahrsummers/xcconfigs` as a dependency in my framework's `Cartfile.private` file ([as seen in ReactiveCocoa](https://github.com/ReactiveCocoa/ReactiveCocoa/blob/swift-development/Cartfile.private)):

```none
github "jspahrsummers/xcconfigs"
```

Then I referenced my framework in another project's `Cartfile` file:

```none
github "akashivskyy/afnetworking-fmwk" "master"
```

Running `carthage update` fails with the following error:

```none
The file "Release.xcconfig" couldn't be opened because there is no such file.
The file "iOS-Framework.xcconfig" couldn't be opened because there is no such file.
Build setting PRODUCT_NAME undefined.
```

Clearly, `xcconfigs` is not being fetched for my framework dependency. Is there a way to  checkout that dependency, without putting it into the global `Carthage/Checkout` folder?

How do you guys achieve this in ReactiveCocoa?

**Comment by jspahrsummers** [comment]
ReactiveCocoa uses its Carthage dependencies as submodules, so the submodule will exist regardless of whether it's in `Cartfile` or `Cartfile.private`.

More generally, though, I'm not sure you'll be able to use xcconfigs in this way, since Xcode relies upon finding them in a very specific location (which will change depending on which project is including your framework). You can just use plain Git submodules or subtrees instead.

**Comment by akashivskyy** [comment]
Okay, sounds clear. Thanks for clarification! :+1:
