### ISSUE TITLE
Intermittent copy-framework errors in lipo "changed since opened (Undefined error: 0)"

### ISSUE THREAD

**Issue by mikemee** [Carthage/Carthage#2835]
* carthage install method: [ ] .pkg, [X] homebrew, [ ] source

* `which carthage`: `/usr/local/bin/carthage`

* `carthage version`:  `0.31.2`

* `xcodebuild -version`: 

Xcode 10.3
Build version 10G8

* Are you using `--no-build`?  no
* Are you using `--no-use-binaries`?  no
* Are you using `--use-submodules`?   no
* Are you using `--cache-builds`? no
* Are you using `--new-resolver`?  no

**Cartfile**
```
github "realm/realm-cocoa" "v3.14.2"
```

**Carthage Output**

Using this from a shell script, it works about 19 times out of 20, both locally and running under Xcode Server CI.  But one out of 20 times (approximately), it fails.
```
/usr/local/bin/carthage copy-frameworks
```

**Actual outcome**
Summary:
```
/usr/bin/lipo: Input file: [....]/Build/Products/Debug-iphonesimulator/Realm.framework.dSYM
   /Contents/Resources/DWARF/Realm changed since opened (Undefined error: 0)
```

Full output:
```
A shell task (/usr/bin/xcrun lipo -remove arm64 -output /Users/xcodeserver/Library/Caches/XCSBuilder/Bots/37aacdc612415d6b5c483fbdcd014cf1/DerivedData/Build/Products/Debug-iphonesimulator/Realm.framework.dSYM/Contents/Resources/DWARF/Realm /Users/xcodeserver/Library/Caches/XCSBuilder/Bots/37aacdc612415d6b5c483fbdcd014cf1/DerivedData/Build/Products/Debug-iphonesimulator/Realm.framework.dSYM/Contents/Resources/DWARF/Realm) failed with exit code 1:
fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: Input file: /Users/xcodeserver/Library/Caches/XCSBuilder/Bots/37aacdc612415d6b5c483fbdcd014cf1/DerivedData/Build/Products/Debug-iphonesimulator/Realm.framework.dSYM/Contents/Resources/DWARF/Realm changed since opened (Undefined error: 0)

Command PhaseScriptExecution failed with a nonzero exit code
```

**Expected outcome**

Framework is copied.

**Discussion**

We have about 30 mins worth of automated tests and use Realm in the app. Our theory is that this failure is happening due to Xcode using more parallelism in the builds, but we really have no idea.  It shows up in CI about 1/20 times. It shows up locally more often when using a 4 core developer machine and the Xcode keyboard command `Shift + Command + U`, to build and run tests.

**Comment by mikemee** [comment]
Perhaps related: #2658, #2531

**Comment by salutis** [comment]
A developer working for @mikemee here. Some more details follow.

The problematic project has two application targets each with its own Copy Carthage Frameworks build phase. Note that these build phases have correct Input Files and Output Files specified. Next, there is a test target which lists the two application targets in its Target Dependencies.

In this configuration, when Build For → Testing is performed, the two application targets are built _simultaneously_ as a dependency of the test target. This is where Carthage _intermittently_ fails with the aforementioned "changed since opened” error.

A workaround that fixes the problem:

```shell
until /usr/local/bin/carthage copy-frameworks
do
  echo "Retrying Carthage copy..." >&2
done
```

**Comment by jdhealy** [comment]
⚠️ I wouldn't recommend potentially-infinitely looping inside an Xcode Shell Script Phase…

〜 Especially with a hardcoded executable path that would effectively result in:

```shell
until /some/non-existent/file-path
do
  echo 'keep logging stuff because the above file path has no executable file there'
done
```

- - -

@salutis, appreciate your solution finding, but wanted to lay out some caveats.

Maybe someone knows of a shell-script–based exponential-backoff-with-retry-limit, floating around on cyberspace?

**Comment by salutis** [comment]
@jdhealy 

> I wouldn't recommend potentially-infinitely looping [...] exponential-backoff-with-retry-limit, floating around on cyberspace?

Agree. Also, a simpler alternative would be to try a couple of times and give up.

**Comment by esteluk** [comment]
We also have seen this when building multiple targets concurrently.

Definitely related: #2788

**Comment by kalkwarf** [comment]
This turns out to be two separate, yet similar problems. The first was Carthage itself would sometimes step on itself. That was fixed in https://github.com/Carthage/Carthage/commit/1e72bd389c02ab2641e353f02c9e513262d59d57

The second is Xcode itself will run multiple `carthage` processes in parallel, so the per-process locking wasn't useful. I started writing code to do one process per directory locking, but it got really messy, really quickly, and I wasn't sure I could test it adequately.

What I did instead was wrap the `carthage copy-frameworks` phase(s) in a Python script, which takes out a per-directory lock before running the command. As long as *all* the `copy-frameworks` phases use the same locking mechanism, this works out well. You can probably guess how I discovered _that_ wrinkle.

**Comment by esteluk** [comment]
Still an issue. Mitigated it as above by adding a crude locking mechanism but... it’s not great, and perhaps would make sense as part of copy-frameworks.

There haven’t been any releases in the last months, so imo the bot is a bit keen to mark this as stale.

**Comment by cmontague09** [comment]
Instead of introducing a locking mechanism around `copy-frameworks` to treat it as a critical section of code, you can turn the `Parallelize Build` option off on that scheme. That will also fix the issue if you are willing to accept a non-parallelized build since the problem only arrises when multiple `copy-frameworks` are called in parallel.
