### ISSUE TITLE
Carthage build time takes way too long.

### ISSUE THREAD

**Issue by brummetj** [Carthage/Carthage#2918]
* carthage install method: [ ] .pkg, [ x ] homebrew, [ ] source
* `which carthage`: /usr/local/bin/carthage
* `carthage version`: 0.34.0
* `xcodebuild -version`: Xcode 11.2.1
Build version 11B53
* Are you using `--no-build`? sometimes
* Are you using `--no-use-binaries`?  sometimes
* Are you using `--use-submodules`? sometimes
* Are you using `--cache-builds`? sometimes
* Are you using `--new-resolver`? no

** Description **

Every time I need to build my dependencies for iOS projects. Carthage takes about 20 years to pull the github project down, and build the schemes. Especially if it's a brand new project, also if I just need one change of dependency it seems to have to go through and rebuild each project scheme. 

This can sometimes take up to 10 minutes each build if the dependency list if very large with multiple different projects. Am I just using carthage wrong ? 

I know you want to preserve "simplicity" as seen in the "contributing guidelines" 

But I would really like to this project multi-threaded out where it can pull and build dependencies in parallel.... speeding up the build time would be huuugeeee ( donald trump voice ). 

If making parallelizing it is too much, maybe I'm just using Carthage wrong? I know that when i use cocoapods, building the dependencies is really fast, but it can be annoying having to deal with cocoapods. 

Let me know what you think!

**Comment by DavidBrunow** [comment]
Mind sharing a little more about how you are using Carthage? If you are using it to pull in public dependencies could you share the Cartfile? Or are you using it for internal dependencies?

**Comment by brummetj** [comment]
I usually use it by doing a 'Carthage bootstrap' or 'Carthage update', sometimes targeting just iOS, its with internal dependencies so I can't share the cartfile :/

**Comment by DavidBrunow** [comment]
If you use the `—use-submodules` functionality in Carthage with a workspace that includes your main app and your Carthage dependencies I believe you can create something somewhat similar to the build system that you get with Cocoapods, with the large disclaimer that I haven’t used Cocoapods in a very long time. Using Carthage that way will get you the benefits of Xcode’s build caching so that only changed files are rebuilt.

All that being said, I don’t like using Carthage that way although I have needed to a time or two. My preference is to treat each of our internal frameworks as though they were frameworks provided by a vendor — they have a documented public API and development in those frameworks is done independently from the main app against unit tests and a test harness app.

Regarding this statement:

> also if I just need one change of dependency it seems to have to go through and rebuild each project scheme.

Y’all might be able to improve this behavior with pre-built binaries using Carthage’s `archive` functionality. 

Alternatively, I believe you can specify that you only want to update a specific dependency when invoking `carthage update`.

**Comment by ikesyo** [comment]
> Alternatively, I believe you can specify that you only want to update a specific dependency when invoking `carthage update`.

👍 for this. And also I recommend you to use `--cache-builds` option and `--platform ios` option.
