### ISSUE TITLE
Why do I see "you used a password to access an endpoint through the GitHub API" ?

### ISSUE THREAD

**Issue by gilsdav** [Carthage/Carthage#3022]
Can I know why and how your tool get my password without I give it and without he asked access to my password store ?

```
Hi ...,

On ... you used a password to access an endpoint through the GitHub API using org.carthage.CarthageKit/0.35.0:

https://api.github.com/repositories/2826918/releases/tags/72e0fa9e62d56e5bbb3f67e9cfd5aa85841735bc

Basic authentication using a password to the API is deprecated and will soon no longer work. Visit https://developer.github.com/changes/2020-02-14-deprecating-password-auth/ for more information around suggested workarounds and removal dates.

Thanks,
```

For me it's a credential theft !

**Comment by tmspzz** [comment]
Hello, thanks for opening an issue. 

Carthage uses git to check out repositories. You gave git access to your credentials and git is using them to access GitHub. Carthage doesn't access your credentials.

**Comment by gilsdav** [comment]
Thanks for your answer.
I would have preferred to see a message "can we get your git credentials?".

So I have another question: What Github API is used for in this project ?

**Comment by tmspzz** [comment]
> I would have preferred to see a message "can we get your git credentials?"

This is not needed since you run carthage with your system user, so it can access any file or program your user can access.

> So I have another question: What Github API is used for in this project ?

For example the "release" api to get Carthage's version number. 

However what you are seeing related to accessing git, rather than the GitHub Api. I linked the relevant pieces of code above.
You're welcome to survey the rest of the code and build the project yourself.
