### ISSUE TITLE
Confusing tag selection for Cartfile.resolved if there are multiple sibling tags

### ISSUE THREAD

**Issue by ilammy** [Carthage/Carthage#3032]
* carthage install method: [ ] .pkg, [X] homebrew, [ ] source
* `which carthage`: /usr/local/bin/carthage
* `carthage version`: 0.35.0
* `xcodebuild -version`: Xcode 11.2.1, Build version 11B500
* Are you using `--no-build`? No
* Are you using `--no-use-binaries`? No
* Are you using `--use-submodules`? No
* Are you using `--cache-builds`? No
* Are you using `--new-resolver`? No

**Cartfile**
```
github "cossacklabs/themis" ~> 0.13.1
```

**Carthage Output**
```
$ carthage update
*** Fetching themis
*** Downloading binary-only framework openssl-static-MacOSX at "https://raw.githubusercontent.com/cossacklabs/openssl-apple/cossacklabs/carthage/openssl-static-MacOSX.json"
*** Downloading binary-only framework openssl-static-iPhone at "https://raw.githubusercontent.com/cossacklabs/openssl-apple/cossacklabs/carthage/openssl-static-iPhone.json"
*** Checking out themis at "gothemis/v0.13.1"
*** Downloading binary-only framework openssl-static-iPhone at "https://raw.githubusercontent.com/cossacklabs/openssl-apple/cossacklabs/carthage/openssl-static-iPhone.json"
*** Downloading openssl-static-iPhone.framework binary at "1.1.107"
*** Downloading binary-only framework openssl-static-MacOSX at "https://raw.githubusercontent.com/cossacklabs/openssl-apple/cossacklabs/carthage/openssl-static-MacOSX.json"
*** Downloading openssl-static-MacOSX.framework binary at "1.1.107"
*** xcodebuild output can be found in /var/folders/w4/4_6vyx_949nb13hv3cpmpsfc0000gn/T/carthage-xcodebuild.1k9k8H.log
*** Building scheme "ObjCThemis (iOS)" in ObjCThemis.xcodeproj
*** Building scheme "ObjCThemis (macOS)" in ObjCThemis.xcodeproj
*** Building scheme "Themis (macOS)" in Themis.xcodeproj
*** Building scheme "Themis (iOS)" in Themis.xcodeproj
```

**Actual outcome**
Carthage selects the `gothemis/v0.13.1` tag, writes it into Cartfile.resolved, and uses it to fetch dependencies.

**Expected outcome**
Carthage should use the `0.13.1` tag which is closer to the requested version.

**Background**
Themis uses monorepo approach, with Swift/Objective-C library being developed alongside Go library (and many others). In order to support Go modules, tags have to be duplicated so for each release there is a `X.Y.Z` tag for normal people, and `gothemis/vX.Y.Z` for gophers, both pointing to the same commit. For some reason Carthage likes to choose the Go tag instead of, arguably, more natural tag without all that fluff.

This does not really cause any issues as both tags are anchored at the same commit (and normally should not move after a release), but it's a weird and surprising behavior nevertheless.

**Comment by tmspzz** [comment]
Thanks for opening an issue. I'm not sure why this is atm but it's likely to affect every project using carthage with great side effects. Thus I don't think the behaviour is likely to change.

**Comment by elliottwilliams** [comment]
I think this issue is worse than @ilammy let on. AFAICT, the bug is in `withSemanticVersion(_:)`: https://github.com/Carthage/Carthage/blob/38c2dcb1601bd43c52e4613312ffea623298d86d/Source/CarthageKit/Version.swift#L399-L408

If a repo has _any_ non-semantically-versioned tag, it will _always_ satisfy `Version.isSatisfied(by:)`. At work, we hit this bug when someone accidentally pushed a tag to remote called "list" and broke dependency resolution for everyone.

@tmspzz I can't think of a Cartfile that would intentionally rely on this behavior. If you wanted to pin to a non-semantic tag, you'd use a `.gitReference`. Would you entertain a fix that changes this function to ignore non-semantic tags when a semantic version specifier is used?

Without a fix:
* we should at least document this as a known issue (happy to volunteer to do so)
* repos which must publish non-semantic tags, like @ilammy's, must communicate to their users that they can _never_ use a semantic version requirement on that repo.

**Comment by tmspzz** [comment]
https://github.com/Carthage/Carthage/pull/2406#discussion_r179121622
