### ISSUE TITLE
Cartfile repos != Cartfile.resolved repos

### ISSUE THREAD

**Issue by iamjason** [Carthage/Carthage#305]
It seems like there is some caching going on.

Repos _not_ included in the Cartfile are being fetched and included.  

e.g. the Cartfile has two repos and after  'carthage update' the Cartfile.resolved shows 5 repos

I'm not sure where these old repos are being referenced from.  Can anyone point me in the right direction to prevent repos _not_ in the Cartfile from being updated/included?

Thanks!

**Comment by jspahrsummers** [comment]
Those are being included because they are [dependencies of your dependencies](https://github.com/Carthage/Carthage/blob/178262e951f670b959c0c68affd5864e703b22ce/Documentation/Artifacts.md#cartfileresolved). You want them in there, so that versions are pinned recursively throughout your dependency graph.

There's no way to disable this, because it'd be a Bad Idea to pretend those dependencies don't exist.

**Comment by iamjason** [comment]
Thanks for the explanation!

**Comment by jspahrsummers** [comment]
No problem. :sparkles:
