### ISSUE TITLE
Release a new version of Carthage with the XCFrameworks change!

### ISSUE THREAD

**Issue by 1oo7** [Carthage/Carthage#3102]
Master was updated 17 days ago without a new release actually being drafted and released. Could someone please see to it that the release happens, or, perhaps give privileges over the repo to me, so I can do it? Thanks!

**Comment by jesusmateos1234** [comment]
@tmspzz @jdhealy, please we'll in love if you could release a new version

**Comment by EmDee** [comment]
I'm pretty sure "asking" like this will encourage the maintainers to release a version faster 👍 

I can understand the frustration, however, the best thing you guys can do is just build a your own `Carthage` build and use that one.

@maintainers: 

I think what a lot of people, including me, are "criticizing" here is the lack of transparency and communication. 

Looking at #3019, it is apparent that there has been a huge pain for developers since Xcode 12 and @elliottwilliams's implementation fixes that pain. What is the hold up for a new release? Is it "only" a lack-of-time issue or is the current master not release worthy yet? If so, why not? Would it make sense to give more people maintainer rights here, e.g. @elliottwilliams, who has been very active lately?

**Comment by elliottwilliams** [comment]
I've been given membership status and am working with the other folks to prepare a release! Reasons for it not being out: we all have day jobs, time off during the holidays, etc. I've been mostly offline for the past two weeks.

I think that master is currently release-worthy, and from what I can tell a number of people have successfully integrated it into their projects. There's more we need to do with xcframeworks (namely support for `binary` dependencies) but we plan to cut a release before then.

**Comment by 1oo7** [comment]
> I'm pretty sure "asking" like this will encourage the maintainers to release a version faster 👍

That's why I said "please" :D

**Comment by daveknowles** [comment]
@elliottwilliams looking forward to getting the new release, any idea on a timeline for the next version? :)
