### ISSUE TITLE
Parse error: expected submodule commit SHA in output of task (ls-tree -z 5.0.0 Carthage/Checkouts/RxSwift) but encountered:

### ISSUE THREAD

**Issue by gltwy** [Carthage/Carthage#3144]
* carthage install method: [ ] .pkg, [ ] homebrew, [ ] source
* `which carthage`:/usr/local/bin/carthage
* `carthage version`: 0.37.0
* `xcodebuild -version`: 12.3
* Are you using `--no-build`? no
* Are you using `--no-use-binaries`? no
* Are you using `--use-submodules`? no
* Are you using `--cache-builds`? no
* Are you using `--new-resolver`? no

**Cartfile**
```
github "ReactiveX/RxSwift" ~> 6.1.0
github "RxSwiftCommunity/RxDataSources" ~> 5.0.0
```

**Carthage Output**
```
carthage update --platform iOS --use-xcframeworks

*** Fetching RxDataSources
*** Fetching RxSwift
*** Checking out RxSwift at "6.1.0"
*** Checking out RxDataSources at "5.0.0"
Parse error: expected submodule commit SHA in output of task (ls-tree -z 5.0.0 Carthage/Checkouts/RxSwift) but encountered:
```

**Actual outcome**
Parse error: expected submodule commit SHA in output of task (ls-tree -z 5.0.0 Carthage/Checkouts/RxSwift) but encountered:

**Expected outcome**
Parse error: expected submodule commit SHA in output of task (ls-tree -z 5.0.0 Carthage/Checkouts/RxSwift) but encountered:

command: carthage update --platform iOS --use-xcframeworks

how can i fix it? thanks!

**Comment by dephillipsmichael** [comment]
This just started happening to me last night out of nowhere.  Have been using Carthage for years and never ran into this issue.

I tried updating to Carthage 0.3.7, re-cloning the repo, running various different commands, made sure my git creds were using access token instead of basic creds.

This is a major blocker for our team, did you ever solve it?
