### ISSUE TITLE
How should I setup an xcframework with GitHub Release and Cartfile?

### ISSUE THREAD

**Issue by Ricardo1980** [Carthage/Carthage#3206]
* carthage install method: [ ] .pkg, [x] homebrew, [ ] source
* `which carthage`: /usr/local/bin/carthage
* `carthage version`: 0.38.0
* `xcodebuild -version`: Xcode 12.3 Build version 12C33
* Are you using `--no-build`? No
* Are you using `--no-use-binaries`? No
* Are you using `--use-submodules`? No
* Are you using `--cache-builds`? No
* Are you using `--new-resolver`? No

**Cartfile**
```
github "xxxxx-uk/xxxxxxxxxxx" == 66.66.66
```

**Carthage Output**
```
*** No Cartfile.resolved found, updating dependencies
*** Fetching xxxxxxxxxxxx
*** Checking out xxxxxxxxxxxx at "v66.66.66"
*** xcodebuild output can be found in /var/folders/y3/47tk7rfs2j74z85lyy1pzb980000gn/T/carthage-xcodebuild.cplWUv.log
*** Skipped building xxxxxxxxxxxx due to the error:
Dependency "xxxxxxxxxxxx" has no shared framework schemes for any of the platforms: iOS

If you believe this to be an error, please file an issue with the maintainers at https://github.com/xxxxx-uk/xxxxxxxxxxxx/issues/new
```

**Actual outcome**
An error  explained above

**Expected outcome**
xcframework is downloaded from the GitHub Release section and uncompressed

**Description**

Hello,

I'm trying to use the new xcframework feature in version 0.38.0
Evidently, my first step was to update to this version.

Anyway, I have a private repo in GitHub.
It generates a framework (xcframework) and in the "GitHub Releases" section I have a release that has one zip file called: `xxxxxxxxx.xcframework.zip` (and another zip file with the source code)
If you uncompress this file, you get a folder like `xxxxx.xcframework` and inside there is this file:
`Info.plist`
and these folders:
```
ios-arm64
ios-x86_64-simulator
tvos-x86_64-simulator
tvos-arm64
```

I would say everything is OK about that.

Then I have another app and in the carthage file I have:
`github "xxxxxx-uk/xxxxxxxxx" == 66.66.66`

When I run this command:
`carthage bootstrap --use-xcframeworks --use-ssh --platform iOS`

This is what I see:
```
Dependency "xxxxxxxxx" has no shared framework schemes for any of the platforms: iOS

If you believe this to be an error, please file an issue with the maintainers at https://github.com/xxx-uk/xxxxxxxxx/issues/new
```
So, at this point I don't see where the error is.

Is my Cartfile setup properly for a private xcframework that is inside a GitHub Release?
In the Carthage/Checkouts folder I see that the source code associated with my framework, I don't know the reason.
In the Carthage/Build folder, I don't see the xcframework, that is, the uncompressed content of the file that my GitHub release has.
Do I have to generate my xcframework with "carthage archive"?

Do you have any suggestion?
What else can I try?

Thanks a lot for your help.

**Comment by elliottwilliams** [comment]
I wonder if the issue is that you can't make an authenticated request to the GitHub API (and thus Carthage can't see your private repo). I'm not super familiar with how that system works, but I believe it can look up an authorization token using the `GITHUB_ACCESS_TOKEN` environment variable or git-credential(1) ([GitHub.swift](https://github.com/Carthage/Carthage/blob/master/Source/CarthageKit/GitHub.swift)).

So you could generate an API key and `export GITHUB_ACCESS_TOKEN=xxxxxx`, or following the steps in [Caching your GitHub credentials in Git](https://docs.github.com/en/get-started/getting-started-with-git/caching-your-github-credentials-in-git).

`--use-ssh` will fall back to fetching and cloning via ssh (where you presumably have a valid key), so as long as your repo has a buildable xcode project with a shared framework scheme, you'd be able to build from source.
