### ISSUE TITLE
Failed to install apps when using Carthage and Xcode12.5

### ISSUE THREAD

**Issue by soranoba** [Carthage/Carthage#3208]
### What's happened
When we build applications depending on libraries that have both StaticLib and DynamicLib Scheme, the built application failed to install on iOS 14.6.
 I found a workaround that *removes the Scheme for StaticLib in Libraries*, but I don't know the correct solution.

Do you know the solution or cause?
Thanks.

#### Libraries that has a Scheme like this:
- https://github.com/BoltsFramework/Bolts-ObjC
- https://github.com/facebookarchive/SocketRocket

#### Build commands
```bash
carthage build --platform iOS --use-xcframeworks Bolts-ObjC SocketRocket
```

#### Error reason
```
code signature version is no longer supported
```
The reason for the installation failure is the same as in the following link.
https://developer.apple.com/forums/thread/679182

### Environments

* carthage install method: [ ] .pkg, [x] homebrew, [ ] source
* `which carthage`:/usr/local/bin/carthage
* `carthage version`: 0.38.0
* `xcodebuild -version`: Xcode 12.5 (12E262)
* Are you using `--no-build`? no
* Are you using `--no-use-binaries`? no
* Are you using `--use-submodules`?  no
* Are you using `--cache-builds`?  no
* Are you using `--new-resolver`?  no

**Cartfile**
```
github "BoltsFramework/Bolts-ObjC" == 1.9.1
```
and some libraries

**Carthage Output**
```
```

**Comment by elliottwilliams** [comment]
> I found a workaround that _removes the Scheme for StaticLib in Libraries_, but I don't know the correct solution.

That sounds correct: you should link, but not embed static framework in an app. Our readme mentions this under [Build static frameworks to speed up your app’s launch times](https://github.com/Carthage/Carthage#build-static-frameworks-to-speed-up-your-apps-launch-times):

> […]
> You should not add any of static frameworks as input/output files in carthage copy-frameworks Build Phase

Granted, that documentation is a little out of date, as it's written with framework bundles and not XCFrameworks in mind. But the same logic applies: static frameworks should not be embedded, since their executable code is copied directly into the main executable during linking.

I'm going to close this out – let me know if there's something I'm missing or if there's a problem with Carthage here!

**Comment by soranoba** [comment]
@elliottwilliams 

Thank you for your reply. 

We cannot specify which scheme to use when libraries have both of Scheme for Dynamic framework and for Static framework.
This means the same as needing to ask the maintainer to stop offering it in the Static framework.

If possible, Carthage would make sense to look for a Scheme for Dynamic framework when using use-xcframeworks, and a Scheme for Static framework otherwise.
How about it?

**Comment by elliottwilliams** [comment]
I see – and this was not a problem before `--use-xcframeworks`, because Carthage would have organized the static build into `Carthage/Build/<platform>/Static`, right?

If we did the same thing for static xcframeworks, would that solve your problem? Carthage would produce artifacts like

    Carthage/Build/<library>.xcframework
    Carthage/Build/Static/<library>.xcframework

and you'd be able to choose which to integrate.

**Comment by soranoba** [comment]
> because Carthage would have organized the static build into Carthage/Build/<platform>/Static, right?

Yes!!

> If we did the same thing for static xcframeworks, would that solve your problem?

Yes, I think that will solve the problem !!
