### ISSUE TITLE
Carthage building iOS targets even with `--platform Mac` specified

### ISSUE THREAD

**Issue by neilpa** [Carthage/Carthage#322]
I updated to version 0.6 of carthage to try out the `--platform` option. Was hoping this would solve my iOS code signing issues when building Mac-only targets with dependencies on dual target frameworks.

I cloned a clean instance of the carthage repo and tried bootstrapping it with `carthage bootstrap --platform Mac`.  That resulted in carthage building a number of the Mac targets but eventually it tries to build LlamaKit for iOS which fails.

```
=== BUILD TARGET LlamaKit-iOS OF PROJECT LlamaKit WITH CONFIGURATION Release ===

Check dependencies
Code Sign error: No matching codesigning identity found: No codesigning identities (i.e. certificate and private key pairs) matching “iPhone Developer” were found.
```

Full build log https://gist.github.com/neilpa/a23d5533ebac2d9e19cf

**Comment by jspahrsummers** [comment]
This appears to be something funky with how [ReactiveTask](https://github.com/Carthage/ReactiveTask) is configured. If I remove it from the `Cartfile` and `Cartfile.resolved`, bootstrapping works fine.

FWIW, though, Carthage is bootstrapped using `script/bootstrap`, because it would be circular to expect it to bootstrap itself. :wink:

**Comment by neilpa** [comment]
Yea, I was able to repro it when trying to bootstrap just the ReactiveTask repo. I got things working by removing it's LlamaKit dependency from the `Cartfile` but _not_ `Cartfile.resolved` before bootstrapping.
