### ISSUE TITLE
Scheme Build Products Clobber One Another

### ISSUE THREAD

**Issue by stephencelis** [Carthage/Carthage#341]
The following project implements two schemes that produce slightly different frameworks with the same name:

https://github.com/stephencelis/SQLite.swift

The two schemes:

 - SQLite
 - SQLiteCipher

Both produce **SQLite.framework**, but one is compiled with [SQLCipher](http://sqlcipher.net) support.

Carthage builds both schemes but because both produce the same product name, one builds over the other into `Carthage/Build/Mac/SQLite.framework`.

Could the products be disambiguated by scheme somehow?

**Comment by jspahrsummers** [comment]
This is more-or-less by design. It's what allows iOS and Mac schemes to end up with the same product name, for example, which is important for `import` statements in cross-platform code.

Here are the possible workarounds that come to mind:

 1. Decide whether SQLCipher support should be the default or not, and hide the scheme for the non-default case.
 1. Rename the product for the SQLCipher case.
 1. Split SQLCipher support out into another project & repository, which builds upon SQLite.swift somehow.
 1. Maintain SQLCipher support on a different branch which can be explicitly chosen if desired.

None of these are ideal, of course, but I don't think we're in a good position to change the names of products created by Carthage. Hope this helps.

**Comment by stephencelis** [comment]
Makes sense. I was wondering about an extra layer, e.g.:

```
Carthage/iOS/{Project}-{Scheme}/{Product}.framework
```

Not ideal, either, and would make setting Carthage up slightly more complex, but it would be more flexible for projects that have a lot of schemes and/or overlapping build targets.

Unfortunately, most of the solutions above require a maintenance or support cost, though I'll see if your third workaround can avoid that. Thanks!

**Comment by jspahrsummers** [comment]
No problem! Please let us know if you run into anything else.
