### ISSUE TITLE
Error submitting to app store with nested dependencies 

### ISSUE THREAD

**Issue by ryanfitz** [Carthage/Carthage#353]
I have project which requires a lib which itself depends on two dynamic frameworks.  When attempting to submit to the app store I get an error about unsupported architectures x86_64 and i386. I have a run script setup executing the `carthage copy-frameworks`, however, it appears this script does not strip x86_64 from those nested libs. 

I found a temporary workaround which is to manually remove the `Frameworks` dir inside the built framework. For example `rm -rf Carthage/Build/iOS/MyLib/Frameworks` Once I do this I can then submit to the appstore

**Comment by dodikk** [comment]
>> I have project which requires a lib which itself depends on two dynamic frameworks. 

So, the mentioned library is a static one. Do you build it from source or you use a pre-built binary?
Have you tried building the mentioned library as a dynamic framework?

P.S. I'm not involved in the "carthage" project. Just letting you know so that you would not expect too much from me.

**Comment by ryanfitz** [comment]
@dodikk all libraries involved are dynamic. The top level dynamic framework requires two other dynamic libs. My app uses carthage to pull down and build the top level framework, which in turn also pulls and builds the nested frameworks.

**Comment by jspahrsummers** [comment]
Unfortunately, as you've discovered, the `carthage copy-frameworks` command is not really built to handle nested frameworks—primarily because they're quite rare.

Most framework targets should not be copying their dependencies into their own `Frameworks` folder (although there are _occasionally_ reasons to do so). Which project are you using that's set up that way?

/cc @robb regarding `copy-frameworks`

**Comment by ryanfitz** [comment]
@jspahrsummers Perhaps I have something setup incorrectly. This is a private framework that I'm building (and then using in an app) which requires both alamofire and swiftyjson. I'm using carthage for both my private framework and my app. 

It sounds like I may have something incorrectly setup where alamofire and swiftjson are getting copied into the Frameworks dir inside my framework. I was thinking that carthage was automatically building the framework this way when running `carthage update` on my app.

I will look further into how xcode has the project setup and see if there is a way to prevent these frameworks from getting copied and still work.

**Comment by jspahrsummers** [comment]
@ryanfitz That probably means there's a “Copy Frameworks” build phase for your framework target. That should generally be deleted. However, any applications using your framework will then need to link all of its dependencies.

This is generally what you want, though, because it reduces duplication if another dependency wants to link one of those nested frameworks too.

**Comment by ryanfitz** [comment]
@jspahrsummers yup, this is exactly what was happening. 

I'm going to close out this issue, but one suggestion would be to add some additional info to the readme for lib authors. I believe xcode automatically setup the 'Copy Frameworks' phase when I initially created the dynamic lib. I know I never initially setup the build to copy frameworks into my own framework, so this might help others who run into similar issues.

**Comment by z4r** [comment]
HI @ryanfitz and @jspahrsummers 
Can you help me to understand what does it mean `delete "Copy Frameworks" phase`?

**Comment by chrisamanse** [comment]
Deleting the copy-frameworks phase worked for me. In my case, though, I still had to delete the xcodebuild cache (`~/Library/Developer/Xcode/DerivedData`) to prevent xcodebuild using past build artifacts.
