### ISSUE TITLE
Xcode Plugin

### ISSUE THREAD

**Issue by flovilmart** [Carthage/Carthage#371]
That would be just great not to use the command line to update, rebuild, add etc...

**Comment by robb** [comment]
This would certainly be a nice community project, but I doubt it's something we want to support officially.

**Comment by flovilmart** [comment]
Why not? That's a simple wrapper around the command line.
I'm actually working on it, it holds in a single file

**Comment by robb** [comment]
Why support two clients if the CLI works and is reasonably simple to use and maintain?

Making it official would mean we'd be willing to maintain it for the foreseeable future, even though there isn't even an official Xcode plugins API (right?)

Of course, it's certainly valuable and :sparkling_heart: for putting in the effort.

**Comment by flovilmart** [comment]
It doesn’t take any energy to support as it’s a single 100 lines of code that take the default arguments from the CLI :)

**Comment by mdiep** [comment]
We might add some scripts that you can add as build phases, but we're pretty against Xcode plugins. If Xcode had an official API, things would be different.

**Comment by flovilmart** [comment]
An xcode plugin is a simple bundle, which is properly documented. In the matter of just adding a menu item to perform the default basic actions, there’s not Voodoo or private API called.




The only difference between a ‘regular' and the xcplugin are 3 keys in the info.plist file.




With the current architecture of Carthage, it is however fairly complicated to reuse the base commands as they are not exposed with a simple API format through Carthage kit.




Is there a refactoring scheduled in order to have something simple like:




let carthage = CarthageKit()

carthage.build() etc..

**Comment by robb** [comment]
Again, if you like to provide an Xcode plugin for people to use, go for it, but we'd rather not.

**Comment by flovilmart** [comment]
So would you rather make the CarthageKit more usable and documented to perform common tasks? And remove logic from the CLI wrapper? Or should I submit a PR for the rearchitecture?




Also, that would be thoughtful to add build instructions to the CONTRIBUTING.md




Any other method but script/bootstrap leads to an unusable project

**Comment by robrix** [comment]
We’ve typically viewed CarthageKit’s charter as an interface for other tools to ingest Cartfiles and dependency graphs and the like. Extending that to include e.g. building would entail significant engineering effort, because it would no longer be able to assume anything from its environment.

Unless I’m misunderstanding something, that sounds like a _lot_ more effort than simply shelling out to run `carthage build`.

It might be valuable for us to consider having thinner commands with even more of their logic living in CarthageKit, but in the meantime, I’d recommend shelling out with `NSTask`, `system`, or [`ReactiveTask`](https://github.com/Carthage/ReactiveTask/) for the commands. (Obviously you would still want to link against CarthageKit if you wanted to e.g. list the dependencies in the plugin’s UI.)

**Comment by robrix** [comment]
I’m going to close this issue out since we’re disinterested in maintaining an Xcode plugin.

**Comment by jspahrsummers** [comment]
I would like to note, as well, that nobody is saying _this shouldn't be built_. Rather, we just don't want to complicate Carthage by introducing too many features, and we don't want to accept the maintenance burden for a feature that seems out of scope.

But part of the beauty of Carthage and CarthageKit is that _it should be easy to build on top of_. The tool is simple and modular, so there's nothing to preclude you from writing and releasing an Xcode plugin! We'd just rather not have it be part of the “official” distribution, for simplicity's sake.
