### ISSUE TITLE
Removing Commit Tags/Versions

### ISSUE THREAD

**Issue by engineeringman** [Carthage/Carthage#401]
After accidentally labeling a commit with a tag (version), we were unable to successfully remove the tag.

For example, say our latest version is 0.1.0.  We pushed a commit, and accidentally tagged it with 0.11, rather than the intended 0.1.1.

We removed the tag using:

```
git tag -d 0.11
git push origin :refs/tags/0.11
```

and re-tagged the latest release with 0.1.1.  However Carthage insists on pulling tag 0.11, despite the fact that it doesn't exist anymore.

We attempted to specify the correct version in the Cartfile, which worked, however Carthage still reverts to tag 0.11 after undoing the Cartfile change.

**Comment by jspahrsummers** [comment]
This is because Carthage maintains a private cache of the repositories you use, to avoid expensive re-fetching every time.

Carthage expects that tags are immutable (as they should be :wink:), so deletions, edits, etc. will generally require some manual fixing—in which case, `rm -rf ~/Library/Caches/org.carthage.CarthageKit` should be good enough.

**Comment by engineeringman** [comment]
Simple enough!

We had noticed the directory Caches/carthage, but I didn't catch that directory.  I seemed to recall looking for com.carthage...  :confounded: 

Just replying to confirm removing it fixed our concerns.

Thank you!

**Comment by jspahrsummers** [comment]
No problem!
