### ISSUE TITLE
com.apple.product-type.tool and iphonesimulator building

### ISSUE THREAD

**Issue by kompozer** [Carthage/Carthage#410]
I have following setup: A project with 3 targets:
* `framework-ios`
* `framework-osx`
* `consoletool-osx` (should only be build for OS X)

plus 3 schemas called similar

I’m trying to build for iOS only with `carthage update --platform iOS` and it fails, cause of trying to build the `consoletool-osx` while using simulator SDK. Here is full log:
```
Build settings from command line:
     SDKROOT = iphonesimulator8.2

=== BUILD TARGET consoletool-osx OF PROJECT framework WITH CONFIGURATION Release ===

Check dependencies
target specifies product type 'com.apple.product-type.tool', but there's no such product type for the 'iphonesimulator' platform
```

How can I prevent `Carthage` to build the `consoletool-osx` for the simulator sdk?

**Comment by jspahrsummers** [comment]
You could hide the `consoletool-osx` scheme in Xcode to prevent it from building automatically.

**Comment by kompozer** [comment]
Hm, but this seems more of a workaround then a solution, no?

**Comment by mdiep** [comment]
It does seem like we should be ignoring the tool product type on iOS.

**Comment by jspahrsummers** [comment]
Carthage only builds schemes that _include_ a framework product, but it has no way of skipping _targets within a scheme_ that have different product types. Schemes aren't divisible like that.

Since the `consoletool-osx` scheme depends upon the framework target, Carthage sees that the scheme will result in at least one framework product, and builds it.
