### ISSUE TITLE
Stricter git tag to semantic version mapping

### ISSUE THREAD

**Issue by neilpa** [Carthage/Carthage#428]
Currently carthage allows any prefix string in tags when attempting to parse out semantic versions. This works as intended for tags like `v1.2.3` or `version-4.5.6`. However, the RAC repo has a few tags like `swift-on-carthage-3.0.2` which are problematic since they trump `v3.0-beta.1` if you use something like `~> 3.0` in your Cartfile.

I explored a couple fixes in the resolver and version sorting that would de-prioritize non `v[ersion][-]` tag prefixes but still allow others. However, that got complicated quickly and could lead to unexpected results. Alternatively the tag to version mapping could be stricter in the allowed prefixes. That would always lead to consistent results but puts an extra burden on projects that don't follow the prescribed prefix scheme.

Thoughts?

**Comment by jspahrsummers** [comment]
I think the current implementation is fine. In fact, those RAC tags were specifically created to test Carthage anyways, so arguably there's not a real problem here (besides my obnoxious use of those tags :trollface:).

If we're okay being Bad Citizens™, I think we could just delete those tags and be done with it. I've seen users intentionally pick them too, so they're doing active harm. :confused:

**Comment by neilpa** [comment]
I inadvertently picked it up which is why I opened the issue. I agree that being stricter is probably the wrong approach since I've seen other projects use various other prefixes for version tags.
