### ISSUE TITLE
When pinned to an exact tag, the SHA is written to Cartfile.resolved instead of the name

### ISSUE THREAD

**Issue by jspahrsummers** [Carthage/Carthage#431]
For example, this `Cartfile` line:

```
github "ReactiveCocoa/ReactiveCocoa" "v3.0-beta.1"
```

will become this in `Cartfile.resolved`:

```
github "ReactiveCocoa/ReactiveCocoa" "233a3c01e32b44610fdcd648d6a8603d7befa626"
```

Unlike a branch or short commit SHA, we can (and should) copy the name as-is, to be consistent with the behavior of version specifiers like `~> 3.0`, which will record the chosen tag name.

**Comment by jspahrsummers** [comment]
I think this also prevents binaries from being found for explicit tag names.

**Comment by brentleyjones** [comment]
It does prevent binaries from being found. Just ran into this myself. I've been hacking the `Cartfile.resolved` to be equal to the tag names.

**Comment by mdiep** [comment]
It doesn't look like #649 fixed the issue of binaries not being found. :confused: /cc @ikesyo

**Comment by ikesyo** [comment]
@mdiep Did you check that with `github "ReactiveCocoa/ReactiveCocoa" "v3.0-beta.1"`?

I've just tested about that, `github "ReactiveCocoa/ReactiveCocoa" "v2.5"` works well, but `github "ReactiveCocoa/ReactiveCocoa" "v3.0-beta.1"` does not. I think that the latter is a prerelease version, so that is rejected by [`binaryFrameworksCanBeProvidedByRelease()`](https://github.com/Carthage/Carthage/blob/01c344c4fb8e1714bd0266d4ccb920282611db94/Source/CarthageKit/Project.swift#L545-L548).

**Comment by mdiep** [comment]
@ikesyo Oops! You're right. Thanks!

**Comment by mdiep** [comment]
On second thought, I don't think we should disqualify binary frameworks because they're pre-release. We shouldn't resolve to a pre-release unless the user has specified that tag; but if they have, we should use the binary.

**Comment by ikesyo** [comment]
@mdiep I agree. I'll tackle it.
