### ISSUE TITLE
Allow specifying which framework to build in Cartfile and/or as a CLI argument

### ISSUE THREAD

**Issue by jpsim** [Carthage/Carthage#437]
Some git repositories have frameworks in multiple Xcode projects (`Realm.xcodeproj` and `RealmSwift.xcodeproj` in https://github.com/realm/realm-cocoa).

Or some git repositories have many framework schemes.

In these cases, it would be beneficial to be able to specify which framework to build in a Cartfile (`github "realm/realm-cocoa" (RealmSwift) ~> 0.91.5`) and/or as a CLI argument (`--framework RealmSwift`).

Specifying a framework would speed up build times, increase Carthage's flexibility and make it possible for Carthage to support building frameworks that it currently cannot.

Instead of only building schemes in the first Xcode project found (see [`CarthageKit/Xcode.swift#L921-L934`](https://github.com/Carthage/Carthage/blob/0.6.5/Source/CarthageKit/Xcode.swift#L921-L934)), Carthage could search all Xcode projects for the given scheme. This would make Carthage support repos with frameworks specified in different Xcode projects.

I'd be very happy to make a PR which adds this functionality, but I thought it best to discuss it here first to settle on a design. Especially with regards to Cartfile syntax and command line argument name.

Thanks!

**Comment by jspahrsummers** [comment]
I responded to a similar suggestion elsewhere, but search is failing me, so I'll try to recap my response here:

Unfortunately, this would introduce some significant complexity. It's not immediately obvious, because the “direct dependency” case is fine, but if you have two projects that both depend on X, what should happen if they depend on different project paths? Building both may not be correct, but failing might not be correct either.

Ultimately, it's a lot simpler to build the canonical product list every time.

**Comment by Dschee** [comment]
I know this topic is old, but I‘m asking myself: If the only problem with this feature is dependency resolution, why don‘t we restrict it to app projects only?

In my experience app projects are the place where this feature is needed the most and implementing it for that only and ignoring it when the Cartfile is part of dependency resolution should be straightforward.

From my point of view the simplest way to get this to work is to simply introduce something like an „Ignorefile“ which simply is a list of framework names to ignore when building. The file could be named ‚Cartfile.ignore‘. This would also cover more complicated cases like when including Moya into a project, which also has variants for reactive programming and therefore includes RxSwift and more (those take up quite some time).

Actually Moya is the reason I searched for this issue, cause they are currently discussing if they should split the project just for Carthage users and the common ground so far is „no“, so I‘m asking myself why this is still not solved in Carthage.

**Comment by BobElDevil** [comment]
The most recent related issue on this that's still open is #1227 if you want to see more discussion on it

**Comment by Dschee** [comment]
Thanks for the pointer, I'll have a look there.

**Comment by Dschee** [comment]
> Unfortunately, this would introduce some significant complexity. It's not immediately obvious, because the “direct dependency” case is fine, but if you have two projects that both depend on X, what should happen if they depend on different project paths? Building both may not be correct, but failing might not be correct either.

Having thought about this for along, why could it actually "not be correct" if we were building both project paths that were defined anywhere? I don't see how building more schemes should lead to an issue – that's actually how it is right now without any option to exclude schemes!

**Comment by flockoffiles** [comment]
Sorry for the dumb question, but was there any progress on either this issue or #1227 ?
I have a framework which must support both CocoaPods and Carthage.
I made two different targets for them, but both of the schemes must be shared.
The problem is that Carthage tries to build them both, and the one that needs CocoaPods fails.
Is there any way to make Carthage build only one of the two shared schemes?

If there is no known solution/work-around, I will have to refuse supporting Carthage, which would be a shame :-(
