### ISSUE TITLE
Skip projects without shared dynamic framework schemes

### ISSUE THREAD

**Issue by neonichu** [Carthage/Carthage#476]
I'm toying around with ways how we can make the CocoaPods pod-template work with Carthage as well, by default (see CocoaPods/pod-template#104), and by extension the project CP generates. The original idea was simply setting the right scheme to shared, but that lead me to some confusing behaviour regarding Carthage's treatment of workspaces.

I have the following setup (see <https://github.com/contentful-labs/Stargate/tree/master/Example> for the project):

- `Pods/Pods.xcodeproj` - the project which contains framework targets for the CocoaPods being used (this is not present in the repo, as it is automatically created when running `pod install`)
- `StargateExample.xcodeproj`, which contains application targets, etc. - it is the project the user would create manually
- `StargateExample.xcworkspace`, automatically created by CP, references the user project and the Pods project.

Sharing the framework scheme for the CocoaPod we want to use via Carthage doesn't appear to do anything, `carthage build --no-skip-current --verbose` yields no output. My assumption was that Carthage would pick the workspace in favour of the project, but I guess that is not correct?

Interestingly enough, creating an empty project with some schemes which share names with the ones from the `Pods.xcodeproj` leads to the correct thing happening, Carthage will build those schemes using the workspace, simply ignoring the empty dummy project. I have created a small script (see <https://gist.github.com/neonichu/b77d7a1efc3e0ec568e1>) which automates this, but ideally, this would not be needed.

It seems to me that Carthage looks at the project for determining which schemes it wants to build (in this case `StargateExample.xcodeproj`, which has no dynamic framework schemes), but does the eventual build using the workspace. This is why providing a dummy project gets the process past the scheme discovery and then works because the schemes I wanted to build are buildable via the workspace.

This seems to be at best confusing to me, would it be feasible to change the scheme discovery so it would use the workspace? Or am I completely on the wrong track and there's some other reason why the approach outlined above cannot work?

**Comment by mdiep** [comment]
Well-behaved projects generally include an `xcodeproj` for building the framework without dependencies and an `xcworkspace` that also builds the dependencies.

Things are structured this way so that any shared dependencies can be built by the top-level project or workspace and found implicitly by the dependencies. This is also why schemes are expected to be shared via the project: Your application would include all the dependencies from their respective `xcodeproj`s.

The workspaces exist so that each framework can be build and tested in isolation. It includes the project and a copy of each dependency so you can build and test while working on that project. That makes them suitable for building via Carthage, but is not how you'd integrate them if you're using submodules with Carthage and building the dependencies as part of your project in Xcode.

**Comment by neonichu** [comment]
Thanks, this certainly clears up why this works like it does. Maybe it would make sense to mention in the README that only the first project file is used for scheme discovery and never any workspaces.

Unfortunately, it is not really feasible for the pod-template to conform to this structure, our auto-generated project does not distinguish between the framework being worked on and its dependencies.

My plan would now be to have a workaround which builds upon the observations about dummy projects mentioned above, e.g. adding a `._.xcodeproj` which makes Carthage's scheme discovery pick the one scheme we care about building for this case. 

I noticed that Carthage skips hidden files when searching for suitable projects (see <https://github.com/Carthage/Carthage/blob/3963af72a4b5e324a72cb5979730529601535317/Source/CarthageKit/Xcode.swift#L179>) - would you be open for a PR which removes `SkipsHiddenFiles` from the enumeration flags?

**Comment by jspahrsummers** [comment]
> would you be open for a PR which removes `SkipsHiddenFiles` from the enumeration flags?

It seems weird to prioritize a project that the user can't easily see or inspect. :confused: 

For example, what if someone wants to modify the pod-template further, and adjust its schemes in some way?

**Comment by neonichu** [comment]
These are valid concerns, but don't really apply for our case since any changes to the actual `Pods.xcodeproj`, as well as the schemes are overwritten each time the user runs `pod install` anyway. So basically the only part that users would adjust are the example project and the Podfile.

**Comment by jspahrsummers** [comment]
Carthage is primarily intended to build projects that are set up for the standard Xcode workflow, where:

* A project file contains one or more framework targets, one or more test targets
* There are perhaps some subprojects for dependencies
* The project is perhaps contained in a workspace that includes dependencies or example apps

Accordingly, we expect that project file to share any schemes that should be included when “building the project,” whether it's for Carthage, continuous integration, other team members, etc.

With regard to the pod-template, it sounds like the issue is that _the project to build_ and _the project's dependencies_ have the same weight, because they are both included in `Pods.xcodeproj`—which has no way to identify “the main project.” This is a very non-standard setup, so that it causes issues with Carthage is unsurprising.

Although we could modify Carthage to support this specific case, the proposed fix (looking at files invisible from the user) or any other special handling would seem to impair the simplicity of the tool, because we now have to consider this special case that only arises when using an autogenerated project from another dependency manager. :wink:

If there's a way that pod-template or Carthage could work around this issue without creating a special case, I'm open to considering it. Ideally, we wouldn't even have to make a behavioral change, but could just tweak pod-template a bit.

Thoughts?

**Comment by neonichu** [comment]
It makes sense to not have this be a special case for either Carthage or CocoaPods. But no matter what we do to the `Pods.xcodeproj`, there'd still be the issue that if the user project would start with a letter < P, it'll be chosen as the source for scheme discovery.

I see two possible ways out of that:

- Have a way to define the scheme to be build could in some other form than through the Xcode project

- Currently, Carthage will simply find no suitable scheme to build for the pod-template, because it'll find the user project first and that contains no dynamic framework schemes. Maybe it would be possible to look at the first workspace instead of the first project in case the first project contains no dynamic frameworks schemes? We could ensure that only relevant schemes are shared from the `Pods.xcodeproj` so that looking at shared schemes available through the workspace would work out fine.

**Comment by jspahrsummers** [comment]
> Maybe it would be possible to look at the first workspace instead of the first project in case the first project contains no dynamic frameworks schemes?

Ah, I like this idea! :sparkles:

I don't know about looking at the _workspace_ instead, because of what @mdiep mentioned about dependencies, but we could probably skip any projects that are missing framework schemes and try the next project instead (and so on). :+1:
