### ISSUE TITLE
Prefer semver tags

### ISSUE THREAD

**Issue by dbworku** [Carthage/Carthage#506]
Carthage uses the latest git tag when checking out. To prevent Carthage from grabbing tags that may be bug or issue related, I suggest filtering semver style tags.

![screen shot 2015-05-30 at 6 11 58 pm](https://cloud.githubusercontent.com/assets/2839631/7899820/4992052e-06f9-11e5-8ab5-4da6b43bb8d2.png)

**Comment by jspahrsummers** [comment]
We do. But in this particular case, it's hard for an algorithm to decide if that's SemVer or not—i.e., maybe it's meant to be version `2.0.0`, and all that other text is just a prefix.

On the other hand, we always filter out version strings that have a _suffix_, since that usually indicates something outside of SemVer—or else a prerelease tag, which we don't currently support.
