### ISSUE TITLE
Reference each platform consistently

### ISSUE THREAD

**Issue by soffes** [Carthage/Carthage#558]
I realize this will break all kinds of things, but we have "iOS", "Mac", and "watchOS" in the Build folder. In Xcode, Apple calls it "OS X" everywhere in build settings.

Should "Mac" be renamed to "OS X" (or "OSX" is the space will cause problems)?

Apple uses Mac to refer to the device not the platform. So it could be iPhone, Mac, and (Apple?) Watch if it was supposed to be device names. Now that watchOS is in there (yay!) does it make sense to change Mac to OS X for consistency?

Totally understand if you guys don't want to do this since this will break so much stuff. Thought about maybe providing a symlink from Mac to OS X as a temporary solution but that seems dumb.

No worries either way on this. Thanks for Carthage! :smiley:

**Comment by jspahrsummers** [comment]
I do think the space in the (proposed) path is of a mild concern—not so much for Xcode or Git, but for custom shell scripts like those that might be found in [Carthage/workflows](https://github.com/Carthage/workflows).

I'll also admit that I picked `Mac` over `OS X` partly because it's more visually distinct from `iOS`.

Neither of these are amazing reasons, but I don't think the breakage would be worth it at this point. Thanks for the suggestion, though!

**Comment by soffes** [comment]
Completely understandable. Thought I'd mention it. I do prefer `Mac` as well although I've been gradually changing my framework targets to `Foo-iOS`, `Foo-OSX`, and `Foo-watchOS`.

Thanks for your thoughtful response! :)

**Comment by jspahrsummers** [comment]
No problem!
