### ISSUE TITLE
Is it possible to specify a subdirectory and/or a scheme name?

### ISSUE THREAD

**Issue by bensarz** [Carthage/Carthage#604]
I find myself looking into the possibility of forking my favourite pods and creating Carthage-enabled projects. I would like to know if it is possible to specify a subdirectory and/or a scheme name in the Cartfile?

**Comment by mdiep** [comment]
That is not currently possible, no. And we believe adding support for something like that adds unnecessary complexity to the project.

**Comment by bensarz** [comment]
So I did a quick test and Carthage was able to pick up on a scheme of a project inside a subfolder.
This works for me. Does Carthage scan all subfolder and execute the first one it finds or all of them?

**Comment by bensarz** [comment]
@mdiep what if there are multiple projects inside the repository? Is there a way to specify which project to use?

**Comment by mdiep** [comment]
No, there's not. I believe we use the first one alphabetically.

We typically structure our repositories with the project containing the framework target at the top level (along with a workspace that also includes dependencies) and with any demo projects in a subdirectory.

**Comment by chrisco314** [comment]
@mdiep: 

I understand and appreciate the approach of keeping things simple, but am trying to find a workflow to replace one aspect of cocoapods that I found useful.  Through the use of cocopods sub projects, I was able to specify real data sources or mock data sources for testing.  I don't mind creating separate projects and separate Cartfiles to support this, but might you have any insight into how or where I would specify the supporting project files so that I could specify one or the other but not both?  And can you point to any articles or guidance on using Carthage for local dependencies in general - pointing to local sub projects, or is all of this outside the realm of possibility for Carthage?  I am not committed to any particular approach, and am just hoping that I have missed something in my web searches.

Thanks.

**Comment by mdiep** [comment]
> Through the use of cocopods sub projects, I was able to specify real data sources or mock data sources for testing. I don't mind creating separate projects and separate Cartfiles to support this, but might you have any insight into how or where I would specify the supporting project files so that I could specify one or the other but not both?

I'm not sure what you mean. Can you elaborate on what you're trying to do?

> And can you point to any articles or guidance on using Carthage for local dependencies in general - pointing to local sub projects, or is all of this outside the realm of possibility for Carthage?

There's an example of how to use a local project in [the documentation about Cartfiles](https://github.com/Carthage/Carthage/blob/master/Documentation/Artifacts.md#example-cartfile).

**Comment by chrisco314** [comment]
@mdiep 

Thanks for the link, I will check it out.  To respond do your question though, I had been using a lightweight take on view models, backed by Core Data's NSManagedObjects.  To speed and simplify the process of figuring out what data a particular view needed though, I started first with a simple Mock object vending static data.   

In the Podspec file for my supporting code / library, I used subspecs to scan either for *CoreData.swift or *.Mock.swift.  Then, in my dependent project, I could specify the version I wanted as either:

    pod 'MyFramework/Model/Mock', :path => 'path/to/data/model'

or

    pod 'MyFramework/Model/CoreData', :path => 'path/to/data/model'

and I could of course specify these in separate files so as to build one or the other.  The end result was that I could isolate the UI that I was working on from nuances of my actual DB layer.  This also helped for UI testing - using static mock models would guarantee me a constant context for testing.

I have since moved other projects to Carthage (and aside from the recurring *git / SHA commit in my ls-tree family of problems*), have been enjoying Carthage and would like to move other projects over.  This however, is a case where I haven't found a solution.

Thanks.

**Comment by mdiep** [comment]
I'm still a little confused about how this is configured—probably because I'm not very familiar with CocoaPods. I think you'll need to use a separate target, configuration, build setting, or runtime variable.

**Comment by ankurp** [comment]
I am also having this same issue. If you look at my project https://github.com/ankurp/Dollar.swift I have a scheme named Cent and Dollar but Cent depends on Dollar so Dollar needs to be built before Cent and throws an error. I do not want to rename the scheme. This issue of specifying scheme for repos that have multiple projects seems important and worth reopening this issue.

**Comment by mdiep** [comment]
The next version of Carthage will build all the frameworks in the repository.
