### ISSUE TITLE
Carthage 0.8.0 hanging on update

### ISSUE THREAD

**Issue by hkellaway** [Carthage/Carthage#705]
I have the following setup:

Cartfile:
```
github "hkellaway/Gloss" "feature/carthage_support"
```

```
> carthage version
0.8.0
```

But am having indefinite hang whenever I do a `carthage update`

```
> carthage update
*** Fetching Gloss
```

I haven't been able to figure it out looking at other Issues. any thoughts? :confused:

**Comment by ikesyo** [comment]
It seems that because [the Cartfile in that branch](https://github.com/hkellaway/Gloss/blob/feature/carthage_support/Cartfile) have `github "hkellaway/Gloss" "feature/carthage_support"`, Carthage are getting into the infinite loop of fetching the dependency(repository). Cartfile is the list of dependencies for the repository, so if you don't have any dependencies for the library, you don't need to have a Cartfile. If you remove the file, that should work.

**Comment by ikesyo** [comment]
In other words, a Cartfile is equivalent to a Podfile of CocoaPods for library users, not a podspec file.

**Comment by hkellaway** [comment]
i tried using the same Cartfile with a brand new project - same hanging behavior

**Comment by mdiep** [comment]
As @ikesyo mentioned, you've configured Gloss to be a dependency of itself. So when Carthage fetches Gloss, it sees that Gloss is a dependency, so it fetches Gloss, sees that Gloss is a dependency, etc. Or something like that.

You need to fix the Cartfile in that branch so it doesn't specify itself as a dependency.

**Comment by hkellaway** [comment]
alright, thank you both. i think i'm just generally having confusion over how to make my library accessible via Carthage; will submit a different Issue if I can't get further with that.
