### ISSUE TITLE
I can't seem to be able to create projects that can be used as carthage frameworks

### ISSUE THREAD

**Issue by haaakon** [Carthage/Carthage#762]
I've tried this:

1. Create a brand new xcode project
2. Set the scheme to "shared"
3. run "carthage build --no-skip-current --verbose"  in the directory
get this output -> Dependency "testproject" has no shared framework schemes
4. run "xcodebuild -scheme testproject -project testproject.xcodeproj "

builds as normally.
Tried both with GM and latest stable XCode with carthage 0.9.1
Am i missing something? I've exhausted the how-to guide in your readme so i had to ask here :)

**Comment by pazzer** [comment]
I've only started using Carthage today, so don't be suprised if what I suggest here is doesn't wrong, or is just plain wrong, but you could try the following:
1. Make sure your *brand new xcode project* is under version control (git specifically), and that you've made an initial commit.
2. Use ``carthage update``, rather than ``carthage build``
3. I found that Carthage will often report an error like the one you mentioned, but if you ``update`` again **immediately**, miraculously, it can start working. 
4. I think that any time you edit the project containing your framework, you'll need to make a new commit - from what I understand, unless otherwise directed, Carthage checks out the latest commit on the master branch.

**Comment by mdiep** [comment]
When I follow your steps, (3) succeeds. Does your project build a dynamic framework? Can you publish it as a repository somewhere?

**Comment by ikesyo** [comment]
Closing this for now due to inactivity. Feel free to reopen if you have any updates on this.
