### ISSUE TITLE
 [Question] New platform test target linking to wrong instance of a built framework 

### ISSUE THREAD

**Issue by bruceflowers** [Carthage/Carthage#775]
This is slightly off topic, but I imagine you guys might have seen this now that you've started supporting tvOS...

I’m developing a library which initially only supported iOS, and now I’ve added the tvOS framework and test targets. There are dependencies, and those frameworks have already been built using Carthage, one for each architecture (so there is a discreet .framework instance of each library for iOS and tvOS respectively). In build phases, I’ve linked only the tvOS-compatible frameworks to the tvOS framework and test targets.

The test classes are shared between both iOS and tvOS test targets.

Here’s where it gets weird:

When running a test class under the iOS test target which imports a module built for iOS, the tests pass.

When running the same test class under the tvOS test target (which should be linking in the specific tvOS-built version of the module), I get this error:

“Module file was created for incompatible target x84_64-apple-ios8.0…”

First, have you encountered this, and if so, how do you solve it?

**Comment by mdiep** [comment]
Were you able to figure this out?

**Comment by kennebecstars** [comment]
I don't think this is a Carthage-related issue. Check CONFIGURATION_BUILD_DIR because it should help take care of this. Mine is set to CONFIGURATION_BUILD_DIR = $(BUILD_DIR)/$(CONFIGURATION)$(EFFECTIVE_PLATFORM_NAME)
Modules can be created for any platform if the framework target has DEFINES_MODULE and CLANG_ENABLE_MODULES set as YES (and not all frameworks do.)

Linking a framework or a static/dynamic library can be customized by using '-framework' or '-l"library"' in OTHER_LDFLAGS.
