### ISSUE TITLE
Archive fails with watchOS 2 extension

### ISSUE THREAD

**Issue by seboslaw** [Carthage/Carthage#830]
Hey guys,

I'm having a problem archiving a watchOS 2 app with the companion iOS app. My Cartfile is as follows:

```
github "ReactiveCocoa/ReactiveCocoa" "v4.0-alpha.1"
github "Alamofire/Alamofire"
github "SwiftyJSON/SwiftyJSON" >= 2.1.2
```
I've then added the iOS frameworks to my iOS app and the watchOS frameworks to my watchOS app, plus added the "/usr/local/bin/carthage copy-frameworks" run script to my main target (iOS app) - and only there.
However, when trying to add the according dsym files to both my iOS and my watchOS app (iOS dsyms -> iOS app; watch OS dsyms -> watch OS app) and then try to archive, XCode does it's thing but won't open the Organizer afterwards. 
In the system Console I get the following error:
```
06.10.15 15:08:09,490 Xcode[1499]: Cannot make directory /Users/me/Library/Developer/Xcode/Archives/2015-10-06/carthageTest 06.10.15, 15.08.xcarchive/dSYMs/Alamofire.framework.dSYM: File exists
```
This actually makes sense since the Alamofire.framework.dSYM gets added twice (one time from the /Carthage/Build/iOS and one time from the /Carthage/Build/watchOS directory). I've also tried disabling parallel builds for my build scheme, but that doesn't solve the issue.

**Comment by kballard** [comment]
In my experience, having identically-named frameworks for both iOS and watchOS simply does not work well with archiving. For now, I'd suggest just not copying the watchOS dSYMs (for any frameworks that are named the same as the iOS version).

**Comment by NachoSoto** [comment]
When you say "frameworks with the same name", are you referring to the target names or the product names?

**Comment by kballard** [comment]
They're usually the same, but I am specifically referring to the product name. If you have two frameworks named `Foo.framework`, one for iOS and one for watchOS, it can cause problems. If you're building the framework as part of the same workspace, it actually screws up the build process itself when you archive, but as this ticket is documenting, it seems that even when using prebuilt frameworks, when it tries to copy the dSYMs into the archive it will fail if there's two dSYMs with the same name (and since the dSYMs are named after the framework, it makes it a framework collision issue).

**Comment by NachoSoto** [comment]
Using the same product names is the only sensible way to do this.
Are you taking about Xcode 7.0? I filed [this radar](https://openradar.appspot.com/22392501) a while ago, and it's been fixed in Xcode 7.1. Could you verify that the same applies to dSYM files? Otherwise we'll need to file another radar :/

**Comment by kballard** [comment]
If it's fixed that's great news. I'm still using 7.0.1 and we hit this problem when refactoring our app to move code into frameworks.

**Comment by mdiep** [comment]
It sounds like this was fixed in Xcode.
