### ISSUE TITLE
how to use carthage on Xcode bot

### ISSUE THREAD

**Issue by shiratsu** [Carthage/Carthage#852]
I am creating ci environment with Xcode bot.
Carthage is used at my iOS project.
When Xcode bot run integrate,bot put out error.

```
*** Cloning RxSwift
A shell task failed with exit code 128:
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

I have set the following code at Before trigger of Xcode bot.

```
cd shot_for_ph2_by_swift
/usr/local/bin/carthage bootstrap
```

I don know how to resolve this matter.
What should i do?

By the way.
The following command is OK.

```
$ git clone git@github.com:realm/realm-cocoa.git                                                                                                                                           system
Cloning into 'realm-cocoa'...
remote: Counting objects: 49991, done.
remote: Compressing objects: 100% (31/31), done.
remote: Total 49991 (delta 13), reused 2 (delta 2), pack-reused 49958
Receiving objects: 100% (49991/49991), 35.87 MiB | 6.56 MiB/s, done.
Resolving deltas: 100% (34928/34928), done.
Checking connectivity... done.
```

**Comment by evgenyneu** [comment]
Hi, the bot executes 'Before Integration' script under _xcsbuildd user. This user probably does not have access to the remote git repositories. I am using Xcode bots as well but I do not have this problem because I am keeping *Carthage/Build* directory in my git repository.

**Comment by shiratsu** [comment]
Hi @evgenyneu 
Thank you for reprying.
>the bot executes 'Before Integration' script under _xcsbuildd user. 
I am just investigating it.Thank you.

I found the following issue.
https://github.com/Carthage/Carthage/issues/289

According to article, keeping Build in our git repository is not best way,but easy way.
That's why I have tryed to use 'carthage bootstrap'.

**Comment by marcpalmer** [comment]
I am also seeing this and don't understand. I read from other issues that it seems Carthage only uses `https://` for private github repos, so why would it be doing "Host key verification" at all - isn't that SSH specific?

I don't understand how to debug this. How can we get real verbose output or logging out of carthage? We can't reasonably debug this interactively because it is running under and Xcode Server managed user account. It all works fine on a user account I have created.

So we need to understand why Carthage is using host verification (seemingly using SSH not HTTPS) and then what we have to do to make the keys available to the Xcode Server user.

Help would be much appreciated. I'm getting nowhere fast :(

**Comment by marcpalmer** [comment]
I volunteer to write up a "Carthage + Xcode bots" doc page for the wiki when we get this solved

**Comment by marcpalmer** [comment]
OK well I am now in a position where I can get carthage to bootstrap as `_xcsbuildd` user on Xcode Server.

RE: SSH above, I didn't realise I had my Xcode Bot pre-trigger set to pass `--use-ssh` to carthage. That's why it was using host auth and showing the `Host key verification failed` error because the `_xcsbuildd` user had never connected to the github servers over ssh and had a change to store the fingerprints in `known_hosts`.

I'm going to write up a bigger blog post about this whole process once I have completed the process. However for those who wish to use Carthage with private github repos and Xcode bots should be fine with this, on your Xcode Server:

1. Switch to the Bot user: `sudo -u _xcsbuildd /bin/bash`
2. Get the keys ready: generate/put your id_rsa key files in `/var/_xcsbuildd/.ssh/ ` as per the Github instructions. These are *separate* from the keys Xcode Bots generates for you for each bot. Add all the public keys to Github. You have one set for the Xcode Server user, and one set per Bot instance. This means you don't have to fiddle trying to find Xcode's secrets for the keys.
3. Add the public key to your github account's SSH Keys
4. Add the keys to ssh: run `eval "$(ssh-agent -s)"` and then `ssh-add /var/_xcsbuildd/.ssh/id_rsa`
5. Test it works: run `git clone` one of your repos using SSH. This will add github keys to `known_hosts` of the build user, and should clone one of your repos.

If step 5 succeeds you can now try to bootstrap the project with carthage by executing `carthage bootstrap --use-ssh` in the cloned project directory.

If this manages to suck down all your dependencies, you're good to go and can add the carthage command to a pre-trigger in your Xcode Bot setup. 

Why use SSH? It got to the point where storing the HTTPS credentials for the github account would require manipulating keychains on the Xcode Server that Apple clearly don't intend us to mess with. This is code for: I saw a lot of ugly shell scripting to grab Xcode Server secrets, change keychain passwords, open keychains, modify them, change passwords back etc. Seems like a lot of pain for a lot of fragility to me.

**Comment by shiratsu** [comment]
Why use SSH?
Because My repository is on bitbucket.
My bitbucket account is differnt from the following capture.
<img width="1400" alt="2015-10-28 14 17 19" src="https://cloud.githubusercontent.com/assets/918490/10780269/f8e28f02-7d7e-11e5-8dac-675df23a6c77.png">

are there way how to change User Name?
If it is possible,I can use https.

**Comment by jonasman** [comment]
@marcpalmer instructions work fine.
Just some tips here:
in step 2 add a passkey or step 4 won't work. 

The command i used was  `carthage bootstrap --platform ios`

After logging in with `sudo -u _xcsbuildd /bin/bash` you can read the xcode logs in `/Library/Developer/XcodeServer/Logs` log name: `xcsbuildd.log` open this and it will tell you what is the log name for the triggers. 
Open the trigger log and follow there what is happening.
