### ISSUE TITLE
WARNING: Skipping build because the necessary signing identity "iPhone Distribution" is not installed

### ISSUE THREAD

**Issue by funkenstrahlen** [Carthage/Carthage#914]
I just installed carthage via homebrew. Added `github "LeoNatan/LNPopupController"` to my `Cartfile` and ran `carthage update`. However I get this error and do not know why:

```
-> carthage update
*** xcodebuild output can be found in /var/folders/8r/nl9r6g3s2j36ljrhdnky9ng40000gn/T/carthage-xcodebuild.wqFs6J.log
*** Building scheme "LNPopupController" in LNPopupController.xcodeproj
*** WARNING: Skipping build for "iphonesimulator" SDK because the necessary signing identity "iPhone Distribution" is not installed
*** WARNING: Skipping build for "iphoneos" SDK because the necessary signing identity "iPhone Distribution" is not installed
```

I do not have a paid developer account (yet). I use the possibility of iOS9 to launch apps on my personal devices.

Any help?

**Comment by mdiep** [comment]
I'm not really familiar with how iOS 9 works in that regard. But I think you have 2 options:

1. Change the configuration of your project so that you use `carthage checkout --no-use-binaries`. Then add the `.xcodeproj`s from your dependencies directly to your application's project and build the dependencies directly through Xcode.

2. I believe Xcode generated a certificate for you. You'd need to find that certificate in Keychain Access.app, duplicate it, and rename the duplicate to `iPhone Distribution`.

I think you should be able to search and find information about both options. (1) is a standard configuration that's not directly related to not having a developer account. But if you get stuck, you can post a follow-up comment here ask for more help.

Good luck!

**Comment by mdiep** [comment]
Carthage 0.11 turns off code signing for all dependencies.

**Comment by funkenstrahlen** [comment]
> Carthage 0.11 turns off code signing for all dependencies.

That fixed it for me.
