### ISSUE TITLE
Allow scheme selection for a "Cocoapods Subspec"-like behaviour

### ISSUE THREAD

**Issue by dalbin** [Carthage/Carthage#933]
Hello,

I'm using Carthage to install https://github.com/danthorpe/Operations.
But this project use multiple schemes to allow user to choose "**Allow app extension API only**" mode.

During the install, Carthage use the latest scheme, which is `Operations-iOS-Extension`.

Could I specify the scheme to tell Carthage to use `Operations-iOS` ?

**Comment by NachoSoto** [comment]
IIUC `Carthage` should build all available schemes for a given architecture. If not, maybe it should?

**Comment by mdiep** [comment]
Carthage doesn't let you select a scheme. It doesn't yet build all schemes, but there's a PR open to do that (#892).

Is the regular Operations using an API that's not safe for extensions?

**Comment by dalbin** [comment]
Carthage build all available schemes, but `Operations-iOS-Extension` build after `Operations-iOS`, so it replace the Operations.framework in the build folder.
And yes, the regular Operations scheme use unsafe APIs for extension, like HealthKit APIs.

Thank you and sorry for my late reply.

**Comment by dalbin** [comment]
Cartfile : 
```
github "danthorpe/Operations" "development"
```

Trimmed output : 
```
carthage bootstrap --platform iOS`

*** No Cartfile.resolved found, updating dependencies
*** Fetching Operations
*** Checking out Operations at "e9545e5dd0cdef2e5ccbbd2af56150875d07a4f0"
*** xcodebuild output can be found in /var/folders/rp/1vgsv4ld6dg3r18mn47gf0n80000gn/T/carthage-xcodebuild.ZKe7NI.log
*** Building scheme "Operations-iOS" in Operations.xcodeproj
*** Building scheme "Operations-iOS-Extension" in Operations.xcodeproj
                  
                                                                                                                       
ls -la Carthage/Build/iOS/

drwxr-xr-x  7 loic  staff      238 Nov 30 14:01 Operations.framework
drwxr-xr-x  3 loic  staff      102 Nov 30 14:01 Operations.framework.dSYM
```

**Comment by mdiep** [comment]
I think the right thing to do here is for Operations to give it's `Operations-iOS-Extension` version of the framework a different name. That seems appropriate since it has different APIs.

**Comment by dalbin** [comment]
That seems a good solution, but apparently, `PRODUCT_NAME` and `PRODUCT_MODULE_NAME` should be equal, so `import` statements must be renamed.

Is scheme selection will be implemented in a future ?

Thank you.

**Comment by mdiep** [comment]
> That seems a good solution, but apparently, PRODUCT_NAME and PRODUCT_MODULE_NAME should be equal, so import statements must be renamed.

Which seems like a good thing to me if it has different APIs.

> Is scheme selection will be implemented in a future ?

Probably not.

**Comment by dalbin** [comment]
Ok, I will ask the maintainer of Operations what is possible to be fully compatible with Carthage. 

Thank you for clarifying. :+1:

**Comment by danthorpe** [comment]
Hi! I've just been alerted to this problem in #112 - will fix it shortly, by giving the Extension compatible framework a different product name. My bad - not an issue with Carthage. Thanks everyone!

**Comment by danthorpe** [comment]
Hi - related to this, unfortunately, Xcode just doesn't let you keep the same module name but have different product names. So, fixing this is actually a bit harder than I thought.

The problem is this - Have a cross platform framework which builds 7 frameworks:

Platform Name | Application framework | API Extension compatible framework
-----|------|------
iOS | :+1:  | :+1:
watchOS | :+1:  | 
tvOS | :+1:  | :+1:
OS X | :+1:  | :+1:

All of which contain the largely the same source code, with some platform/variant specific things not included. Therefore we need them all to be the same module name, so `import Operations` works regardless of whether it's an extension compatible framework or not.

To get the module name to be consistent you have to set it directly, and once you do this, it's not possible to them change the product name - they have to match.

So, the only thing to do is to create two Xcode projects, one for the 4 standard frameworks, and one for the 3 extension compatible only ones.

This is all setup and working here: https://github.com/danthorpe/Operations/pull/114 (except for some code coverage issues). In the root of the repo (on this branch) there are two Xcode projects, one is called Operations.xcodeproj, the other Extension Compatible Frameworks.xcodeproj. Both have all their schemes shared.

Creating a dummy folder to test how Carthage interprets this, with a Cartfile:

```
github "danthorpe/Operations" "feature/OPR-112_rename_extension_product"
```

produces this:

```
$ carthage update
*** Fetching Operations
*** Checking out Operations at "498b5e25f12fedcaa56899fd98306de3d4cd04e8"
*** xcodebuild output can be found in /var/folders/6j/9k2drdbs1fv9fw5d6wng5yzh0000gn/T/carthage-xcodebuild.rEBoAQ.log
*** Building scheme "OS X Operations" in Extension Compatible Frameworks.xcodeproj
*** WARNING: Skipping build for "macosx" SDK because the necessary signing identity "-" is not installed
*** Building scheme "tvOS Operations" in Extension Compatible Frameworks.xcodeproj
*** Building scheme "iOS Operations" in Extension Compatible Frameworks.xcodeproj
$
```

So, it looks like what happens is that Carthage is building the first .xcodeproj it finds. Is there a way to make Carthage build all the schemes from all the Xcode projects? Ideally, the build artifacts would end up

```
Carthage
  |- Build
    |- Project One Name
      |- iOS
      |- etc
    |- Project Two Name
      |- iOS
      |- etc
```

Or has anyone got any other thoughts?

**Comment by mdiep** [comment]
> So, it looks like what happens is that Carthage is building the first .xcodeproj it finds (listed alphabetically). Is there a way to make Carthage build all the schemes from all the Xcode projects?

Not yet, but there's an open issue #888 and a WIP PR #892.
