### ISSUE TITLE
no umbrella header found for target 'CryptoSwift watchOS'

### ISSUE THREAD

**Issue by mattlanham** [Carthage/Carthage#977]
Hi All,

Hoping you can help with an issue in a repository that uses Carthage (https://github.com/krzyzanowskim/CryptoSwift/issues/169), each time I try to run 'carthage update' I am receiving an error relating to the umbrella header. As you will see in this issue, the maintainer has added a header, but it's still results in the same error.

Any ideas?

**Comment by mdiep** [comment]
The header (https://github.com/krzyzanowskim/CryptoSwift/pull/170) _does_ fix the issue. But since that fix hasn't been included in a release of the framework, you need to specify the `master` branch to get a version that includes the fix.

```
$ cat Cartfile
github "krzyzanowskim/CryptoSwift" "master"
$ carthage update --platform watchos
*** Fetching CryptoSwift
*** Checking out CryptoSwift at "58bba1f8b4fba06dfaa3144c7fcbcfdda5532039"
*** xcodebuild output can be found in /var/folders/xj/sydx1wkd0p147x0k_7v667940000gn/T/carthage-xcodebuild.M1nH9w.log
*** Building scheme "CryptoSwift watchOS" in CryptoSwift.xcodeproj
```

If the project maintainer creates a new release, then won't need to specify the branch.
